//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Frapid.Configuration;
using Frapid.i18n;
using System.Threading.Tasks;

namespace Frapid.i18n.Resources
{
	public class DbErrors
	{
		public static string Get(string key, string tenant = "")
		{
		    if (string.IsNullOrWhiteSpace(tenant))
		    {
		        tenant = TenantConvention.GetTenant();
		    }

			return ResourceManager.GetString(tenant, "DbErrors", key);
		}
		
		/// <summary>
		///   Localized string for The table was not found.
		/// </summary>
		public static string TableNotFound 
		{
			get
			{
				return Get("TableNotFound");
			}
		}
	}
	public class Labels
	{
		public static string Get(string key, string tenant = "")
		{
		    if (string.IsNullOrWhiteSpace(tenant))
		    {
		        tenant = TenantConvention.GetTenant();
		    }

			return ResourceManager.GetString(tenant, "Labels", key);
		}
		
		/// <summary>
		///   Localized string for Flag was removed.
		/// </summary>
		public static string FlagRemoved 
		{
			get
			{
				return Get("FlagRemoved");
			}
		}
		
		/// <summary>
		///   Localized string for Flag was saved.
		/// </summary>
		public static string FlagSaved 
		{
			get
			{
				return Get("FlagSaved");
			}
		}
		
		/// <summary>
		///   Localized string for Successfully imported {0} items.
		/// </summary>
		public static string ImportedNItems 
		{
			get
			{
				return Get("ImportedNItems");
			}
		}
		
		/// <summary>
		///   Localized string for Item duplicated.
		/// </summary>
		public static string ItemDuplicated 
		{
			get
			{
				return Get("ItemDuplicated");
			}
		}
		
		/// <summary>
		///   Localized string for Filter: {0}.
		/// </summary>
		public static string NamedFilter 
		{
			get
			{
				return Get("NamedFilter");
			}
		}
		
		/// <summary>
		///   Localized string for {0} hour(s).
		/// </summary>
		public static string NHours 
		{
			get
			{
				return Get("NHours");
			}
		}
		
		/// <summary>
		///   Localized string for {0} minute(s).
		/// </summary>
		public static string NMinutes 
		{
			get
			{
				return Get("NMinutes");
			}
		}
		
		/// <summary>
		///   Localized string for No instance of form was found.
		/// </summary>
		public static string NoFormFound 
		{
			get
			{
				return Get("NoFormFound");
			}
		}
		
		/// <summary>
		///   Localized string for Processing  your CSV file.
		/// </summary>
		public static string ProcessingYourCSVFile 
		{
			get
			{
				return Get("ProcessingYourCSVFile");
			}
		}
		
		/// <summary>
		///   Localized string for Requesting import. This may take several minutes to complete.
		/// </summary>
		public static string RequestingImport 
		{
			get
			{
				return Get("RequestingImport");
			}
		}
		
		/// <summary>
		///   Localized string for Rolling back changes.
		/// </summary>
		public static string RollingBackChanges 
		{
			get
			{
				return Get("RollingBackChanges");
			}
		}
		
		/// <summary>
		///   Localized string for Successfully processed your file.
		/// </summary>
		public static string SuccessfullyProcessedYourFile 
		{
			get
			{
				return Get("SuccessfullyProcessedYourFile");
			}
		}
		
		/// <summary>
		///   Localized string for Task completed successfully.
		/// </summary>
		public static string TaskCompletedSuccessfully 
		{
			get
			{
				return Get("TaskCompletedSuccessfully");
			}
		}
		
		/// <summary>
		///   Localized string for This field is required.
		/// </summary>
		public static string ThisFieldIsRequired 
		{
			get
			{
				return Get("ThisFieldIsRequired");
			}
		}
		
		/// <summary>
		///   Localized string for Your upload is of invalid file type "{0}". Please try again.
		/// </summary>
		public static string UploadInvalidTryAgain 
		{
			get
			{
				return Get("UploadInvalidTryAgain");
			}
		}
	}
	public class Questions
	{
		public static string Get(string key, string tenant = "")
		{
		    if (string.IsNullOrWhiteSpace(tenant))
		    {
		        tenant = TenantConvention.GetTenant();
		    }

			return ResourceManager.GetString(tenant, "Questions", key);
		}
		
		/// <summary>
		///   Localized string for Are you sure?
		/// </summary>
		public static string AreYouSure 
		{
			get
			{
				return Get("AreYouSure");
			}
		}
		
		/// <summary>
		///   Localized string for The column "{0}" does not exist or is invalid. Are you sure you want to continue?
		/// </summary>
		public static string ColumnInvalidAreYouSure 
		{
			get
			{
				return Get("ColumnInvalidAreYouSure");
			}
		}
		
		/// <summary>
		///   Localized string for Task completed successfully. Return to view?
		/// </summary>
		public static string TaskCompletedSuccessfullyReturnToView 
		{
			get
			{
				return Get("TaskCompletedSuccessfullyReturnToView");
			}
		}
	}
	public class Titles
	{
		public static string Get(string key, string tenant = "")
		{
		    if (string.IsNullOrWhiteSpace(tenant))
		    {
		        tenant = TenantConvention.GetTenant();
		    }

			return ResourceManager.GetString(tenant, "Titles", key);
		}
		
		/// <summary>
		///   Localized string for Actions
		/// </summary>
		public static string Actions 
		{
			get
			{
				return Get("Actions");
			}
		}
		
		/// <summary>
		///   Localized string for Add
		/// </summary>
		public static string Add 
		{
			get
			{
				return Get("Add");
			}
		}
		
		/// <summary>
		///   Localized string for Add a Kanban List
		/// </summary>
		public static string AddAKanbanList 
		{
			get
			{
				return Get("AddAKanbanList");
			}
		}
		
		/// <summary>
		///   Localized string for Add New
		/// </summary>
		public static string AddNew 
		{
			get
			{
				return Get("AddNew");
			}
		}
		
		/// <summary>
		///   Localized string for Add New Checklist
		/// </summary>
		public static string AddNewChecklist 
		{
			get
			{
				return Get("AddNewChecklist");
			}
		}
		
		/// <summary>
		///   Localized string for And
		/// </summary>
		public static string And 
		{
			get
			{
				return Get("And");
			}
		}
		
		/// <summary>
		///   Localized string for Approve
		/// </summary>
		public static string Approve 
		{
			get
			{
				return Get("Approve");
			}
		}
		
		/// <summary>
		///   Localized string for Back
		/// </summary>
		public static string Back 
		{
			get
			{
				return Get("Back");
			}
		}
		
		/// <summary>
		///   Localized string for Cancel
		/// </summary>
		public static string Cancel 
		{
			get
			{
				return Get("Cancel");
			}
		}
		
		/// <summary>
		///   Localized string for Close
		/// </summary>
		public static string Close 
		{
			get
			{
				return Get("Close");
			}
		}
		
		/// <summary>
		///   Localized string for Column Name
		/// </summary>
		public static string ColumnName 
		{
			get
			{
				return Get("ColumnName");
			}
		}
		
		/// <summary>
		///   Localized string for Condition
		/// </summary>
		public static string Condition 
		{
			get
			{
				return Get("Condition");
			}
		}
		
		/// <summary>
		///   Localized string for Create a Flag
		/// </summary>
		public static string CreateAFlag 
		{
			get
			{
				return Get("CreateAFlag");
			}
		}
		
		/// <summary>
		///   Localized string for Create Duplicate
		/// </summary>
		public static string CreateDuplicate 
		{
			get
			{
				return Get("CreateDuplicate");
			}
		}
		
		/// <summary>
		///   Localized string for Create New
		/// </summary>
		public static string CreateNew 
		{
			get
			{
				return Get("CreateNew");
			}
		}
		
		/// <summary>
		///   Localized string for Custom Fields
		/// </summary>
		public static string CustomFields 
		{
			get
			{
				return Get("CustomFields");
			}
		}
		
		/// <summary>
		///   Localized string for Data Import
		/// </summary>
		public static string DataImport 
		{
			get
			{
				return Get("DataImport");
			}
		}
		
		/// <summary>
		///   Localized string for Delete
		/// </summary>
		public static string Delete 
		{
			get
			{
				return Get("Delete");
			}
		}
		
		/// <summary>
		///   Localized string for Delete This Checklist
		/// </summary>
		public static string DeleteThisChecklist 
		{
			get
			{
				return Get("DeleteThisChecklist");
			}
		}
		
		/// <summary>
		///   Localized string for Description
		/// </summary>
		public static string Description 
		{
			get
			{
				return Get("Description");
			}
		}
		
		/// <summary>
		///   Localized string for Edit
		/// </summary>
		public static string Edit 
		{
			get
			{
				return Get("Edit");
			}
		}
		
		/// <summary>
		///   Localized string for Edit This Checklist
		/// </summary>
		public static string EditThisChecklist 
		{
			get
			{
				return Get("EditThisChecklist");
			}
		}
		
		/// <summary>
		///   Localized string for Export
		/// </summary>
		public static string Export 
		{
			get
			{
				return Get("Export");
			}
		}
		
		/// <summary>
		///   Localized string for Export Data
		/// </summary>
		public static string ExportData 
		{
			get
			{
				return Get("ExportData");
			}
		}
		
		/// <summary>
		///   Localized string for Export This Document
		/// </summary>
		public static string ExportThisDocument 
		{
			get
			{
				return Get("ExportThisDocument");
			}
		}
		
		/// <summary>
		///   Localized string for Export to Doc
		/// </summary>
		public static string ExportToDoc 
		{
			get
			{
				return Get("ExportToDoc");
			}
		}
		
		/// <summary>
		///   Localized string for Export to Excel
		/// </summary>
		public static string ExportToExcel 
		{
			get
			{
				return Get("ExportToExcel");
			}
		}
		
		/// <summary>
		///   Localized string for Export to PDF
		/// </summary>
		public static string ExportToPDF 
		{
			get
			{
				return Get("ExportToPDF");
			}
		}
		
		/// <summary>
		///   Localized string for Filter
		/// </summary>
		public static string Filter 
		{
			get
			{
				return Get("Filter");
			}
		}
		
		/// <summary>
		///   Localized string for Filter Condition
		/// </summary>
		public static string FilterCondition 
		{
			get
			{
				return Get("FilterCondition");
			}
		}
		
		/// <summary>
		///   Localized string for Filter Name
		/// </summary>
		public static string FilterName 
		{
			get
			{
				return Get("FilterName");
			}
		}
		
		/// <summary>
		///   Localized string for First
		/// </summary>
		public static string First 
		{
			get
			{
				return Get("First");
			}
		}
		
		/// <summary>
		///   Localized string for Flag
		/// </summary>
		public static string Flag 
		{
			get
			{
				return Get("Flag");
			}
		}
		
		/// <summary>
		///   Localized string for Import Data
		/// </summary>
		public static string ImportData 
		{
			get
			{
				return Get("ImportData");
			}
		}
		
		/// <summary>
		///   Localized string for KanbanId
		/// </summary>
		public static string KanbanId 
		{
			get
			{
				return Get("KanbanId");
			}
		}
		
		/// <summary>
		///   Localized string for KanbanName
		/// </summary>
		public static string KanbanName 
		{
			get
			{
				return Get("KanbanName");
			}
		}
		
		/// <summary>
		///   Localized string for Last
		/// </summary>
		public static string Last 
		{
			get
			{
				return Get("Last");
			}
		}
		
		/// <summary>
		///   Localized string for Loading
		/// </summary>
		public static string Loading 
		{
			get
			{
				return Get("Loading");
			}
		}
		
		/// <summary>
		///   Localized string for Make As Default
		/// </summary>
		public static string MakeAsDefault 
		{
			get
			{
				return Get("MakeAsDefault");
			}
		}
		
		/// <summary>
		///   Localized string for Manage Filters
		/// </summary>
		public static string ManageFilters 
		{
			get
			{
				return Get("ManageFilters");
			}
		}
		
		/// <summary>
		///   Localized string for Next
		/// </summary>
		public static string Next 
		{
			get
			{
				return Get("Next");
			}
		}
		
		/// <summary>
		///   Localized string for No
		/// </summary>
		public static string No 
		{
			get
			{
				return Get("No");
			}
		}
		
		/// <summary>
		///   Localized string for None
		/// </summary>
		public static string None 
		{
			get
			{
				return Get("None");
			}
		}
		
		/// <summary>
		///   Localized string for OK
		/// </summary>
		public static string OK 
		{
			get
			{
				return Get("OK");
			}
		}
		
		/// <summary>
		///   Localized string for Or
		/// </summary>
		public static string Or 
		{
			get
			{
				return Get("Or");
			}
		}
		
		/// <summary>
		///   Localized string for Page {0}
		/// </summary>
		public static string PageN 
		{
			get
			{
				return Get("PageN");
			}
		}
		
		/// <summary>
		///   Localized string for Password
		/// </summary>
		public static string Password 
		{
			get
			{
				return Get("Password");
			}
		}
		
		/// <summary>
		///   Localized string for Previous
		/// </summary>
		public static string Previous 
		{
			get
			{
				return Get("Previous");
			}
		}
		
		/// <summary>
		///   Localized string for Print
		/// </summary>
		public static string Print 
		{
			get
			{
				return Get("Print");
			}
		}
		
		/// <summary>
		///   Localized string for Rating
		/// </summary>
		public static string Rating 
		{
			get
			{
				return Get("Rating");
			}
		}
		
		/// <summary>
		///   Localized string for Reason
		/// </summary>
		public static string Reason 
		{
			get
			{
				return Get("Reason");
			}
		}
		
		/// <summary>
		///   Localized string for Reject
		/// </summary>
		public static string Reject 
		{
			get
			{
				return Get("Reject");
			}
		}
		
		/// <summary>
		///   Localized string for Remove As Default
		/// </summary>
		public static string RemoveAsDefault 
		{
			get
			{
				return Get("RemoveAsDefault");
			}
		}
		
		/// <summary>
		///   Localized string for Return to View
		/// </summary>
		public static string ReturnToView 
		{
			get
			{
				return Get("ReturnToView");
			}
		}
		
		/// <summary>
		///   Localized string for Return to Website
		/// </summary>
		public static string ReturnToWebsite 
		{
			get
			{
				return Get("ReturnToWebsite");
			}
		}
		
		/// <summary>
		///   Localized string for Save
		/// </summary>
		public static string Save 
		{
			get
			{
				return Get("Save");
			}
		}
		
		/// <summary>
		///   Localized string for Save This Filter
		/// </summary>
		public static string SaveThisFilter 
		{
			get
			{
				return Get("SaveThisFilter");
			}
		}
		
		/// <summary>
		///   Localized string for Select
		/// </summary>
		public static string Select 
		{
			get
			{
				return Get("Select");
			}
		}
		
		/// <summary>
		///   Localized string for Select a Column
		/// </summary>
		public static string SelectAColumn 
		{
			get
			{
				return Get("SelectAColumn");
			}
		}
		
		/// <summary>
		///   Localized string for Select a Filter
		/// </summary>
		public static string SelectAFilter 
		{
			get
			{
				return Get("SelectAFilter");
			}
		}
		
		/// <summary>
		///   Localized string for Sign In
		/// </summary>
		public static string SignIn 
		{
			get
			{
				return Get("SignIn");
			}
		}
		
		/// <summary>
		///   Localized string for Untitled
		/// </summary>
		public static string Untitled 
		{
			get
			{
				return Get("Untitled");
			}
		}
		
		/// <summary>
		///   Localized string for Update
		/// </summary>
		public static string Update 
		{
			get
			{
				return Get("Update");
			}
		}
		
		/// <summary>
		///   Localized string for Username
		/// </summary>
		public static string Username 
		{
			get
			{
				return Get("Username");
			}
		}
		
		/// <summary>
		///   Localized string for Value
		/// </summary>
		public static string Value 
		{
			get
			{
				return Get("Value");
			}
		}
		
		/// <summary>
		///   Localized string for Verification
		/// </summary>
		public static string Verification 
		{
			get
			{
				return Get("Verification");
			}
		}
		
		/// <summary>
		///   Localized string for Verify
		/// </summary>
		public static string Verify 
		{
			get
			{
				return Get("Verify");
			}
		}
		
		/// <summary>
		///   Localized string for View
		/// </summary>
		public static string View 
		{
			get
			{
				return Get("View");
			}
		}
		
		/// <summary>
		///   Localized string for Yes
		/// </summary>
		public static string Yes 
		{
			get
			{
				return Get("Yes");
			}
		}
	}
	public class Warnings
	{
		public static string Get(string key, string tenant = "")
		{
		    if (string.IsNullOrWhiteSpace(tenant))
		    {
		        tenant = TenantConvention.GetTenant();
		    }

			return ResourceManager.GetString(tenant, "Warnings", key);
		}
		
		/// <summary>
		///   Localized string for Invalid file extension.
		/// </summary>
		public static string InvalidFileExtension 
		{
			get
			{
				return Get("InvalidFileExtension");
			}
		}
	}
}