//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Frapid.i18n;
using System.Threading.Tasks;

namespace Frapid.i18n.Resources
{
	public class DbErrors
	{
		public static string Get(string key)
		{
			return ResourceManager.GetString("DbErrors", key);
		}
		
		/// <summary>
		///   Localized string for The table was not found.
		/// </summary>
		public static string TableNotFound 
		{
			get
			{
				return Get("TableNotFound");
			}
		}
	}
	public class Labels
	{
		public static string Get(string key)
		{
			return ResourceManager.GetString("Labels", key);
		}
		
		/// <summary>
		///   Localized string for Flag was removed.
		/// </summary>
		public static string FlagRemoved 
		{
			get
			{
				return Get("FlagRemoved");
			}
		}
		
		/// <summary>
		///   Localized string for Flag was saved.
		/// </summary>
		public static string FlagSaved 
		{
			get
			{
				return Get("FlagSaved");
			}
		}
		
		/// <summary>
		///   Localized string for Successfully imported {0} items.
		/// </summary>
		public static string ImportedNItems 
		{
			get
			{
				return Get("ImportedNItems");
			}
		}
		
		/// <summary>
		///   Localized string for Item duplicated.
		/// </summary>
		public static string ItemDuplicated 
		{
			get
			{
				return Get("ItemDuplicated");
			}
		}
		
		/// <summary>
		///   Localized string for Filter: {0}.
		/// </summary>
		public static string NamedFilter 
		{
			get
			{
				return Get("NamedFilter");
			}
		}
		
		/// <summary>
		///   Localized string for {0} hour(s).
		/// </summary>
		public static string NHours 
		{
			get
			{
				return Get("NHours");
			}
		}
		
		/// <summary>
		///   Localized string for {0} minute(s).
		/// </summary>
		public static string NMinutes 
		{
			get
			{
				return Get("NMinutes");
			}
		}
		
		/// <summary>
		///   Localized string for No instance of form was found.
		/// </summary>
		public static string NoFormFound 
		{
			get
			{
				return Get("NoFormFound");
			}
		}
		
		/// <summary>
		///   Localized string for Processing  your CSV file.
		/// </summary>
		public static string ProcessingYourCSVFile 
		{
			get
			{
				return Get("ProcessingYourCSVFile");
			}
		}
		
		/// <summary>
		///   Localized string for Requesting import. This may take several minutes to complete.
		/// </summary>
		public static string RequestingImport 
		{
			get
			{
				return Get("RequestingImport");
			}
		}
		
		/// <summary>
		///   Localized string for Rolling back changes.
		/// </summary>
		public static string RollingBackChanges 
		{
			get
			{
				return Get("RollingBackChanges");
			}
		}
		
		/// <summary>
		///   Localized string for Successfully processed your file.
		/// </summary>
		public static string SuccessfullyProcessedYourFile 
		{
			get
			{
				return Get("SuccessfullyProcessedYourFile");
			}
		}
		
		/// <summary>
		///   Localized string for Task completed successfully.
		/// </summary>
		public static string TaskCompletedSuccessfully 
		{
			get
			{
				return Get("TaskCompletedSuccessfully");
			}
		}
		
		/// <summary>
		///   Localized string for This field is required.
		/// </summary>
		public static string ThisFieldIsRequired 
		{
			get
			{
				return Get("ThisFieldIsRequired");
			}
		}
		
		/// <summary>
		///   Localized string for Your upload is of invalid file type "{0}". Please try again.
		/// </summary>
		public static string UploadInvalidTryAgain 
		{
			get
			{
				return Get("UploadInvalidTryAgain");
			}
		}
	}
	public class Questions
	{
		public static string Get(string key)
		{
			return ResourceManager.GetString("Questions", key);
		}
		
		/// <summary>
		///   Localized string for Are you sure?
		/// </summary>
		public static string AreYouSure 
		{
			get
			{
				return Get("AreYouSure");
			}
		}
		
		/// <summary>
		///   Localized string for The column "{0}" does not exist or is invalid. Are you sure you want to continue?
		/// </summary>
		public static string ColumnInvalidAreYouSure 
		{
			get
			{
				return Get("ColumnInvalidAreYouSure");
			}
		}
		
		/// <summary>
		///   Localized string for Task completed successfully. Return to view?
		/// </summary>
		public static string TaskCompletedSuccessfullyReturnToView 
		{
			get
			{
				return Get("TaskCompletedSuccessfullyReturnToView");
			}
		}
	}
	public class Titles
	{
		public static string Get(string key)
		{
			return ResourceManager.GetString("Titles", key);
		}
		
		/// <summary>
		///   Localized string for Actions
		/// </summary>
		public static string Actions 
		{
			get
			{
				return Get("Actions");
			}
		}
		
		/// <summary>
		///   Localized string for Add
		/// </summary>
		public static string Add 
		{
			get
			{
				return Get("Add");
			}
		}
		
		/// <summary>
		///   Localized string for Add New Checklist
		/// </summary>
		public static string AddNewChecklist 
		{
			get
			{
				return Get("AddNewChecklist");
			}
		}
		
		/// <summary>
		///   Localized string for Back
		/// </summary>
		public static string Back 
		{
			get
			{
				return Get("Back");
			}
		}
		
		/// <summary>
		///   Localized string for Custom Fields
		/// </summary>
		public static string CustomFields 
		{
			get
			{
				return Get("CustomFields");
			}
		}
		
		/// <summary>
		///   Localized string for Delete
		/// </summary>
		public static string Delete 
		{
			get
			{
				return Get("Delete");
			}
		}
		
		/// <summary>
		///   Localized string for Delete This Checklist
		/// </summary>
		public static string DeleteThisChecklist 
		{
			get
			{
				return Get("DeleteThisChecklist");
			}
		}
		
		/// <summary>
		///   Localized string for Edit
		/// </summary>
		public static string Edit 
		{
			get
			{
				return Get("Edit");
			}
		}
		
		/// <summary>
		///   Localized string for Edit This Checklist
		/// </summary>
		public static string EditThisChecklist 
		{
			get
			{
				return Get("EditThisChecklist");
			}
		}
		
		/// <summary>
		///   Localized string for No
		/// </summary>
		public static string No 
		{
			get
			{
				return Get("No");
			}
		}
		
		/// <summary>
		///   Localized string for None
		/// </summary>
		public static string None 
		{
			get
			{
				return Get("None");
			}
		}
		
		/// <summary>
		///   Localized string for Or
		/// </summary>
		public static string Or 
		{
			get
			{
				return Get("Or");
			}
		}
		
		/// <summary>
		///   Localized string for Page {0}
		/// </summary>
		public static string PageN 
		{
			get
			{
				return Get("PageN");
			}
		}
		
		/// <summary>
		///   Localized string for Password
		/// </summary>
		public static string Password 
		{
			get
			{
				return Get("Password");
			}
		}
		
		/// <summary>
		///   Localized string for Rating
		/// </summary>
		public static string Rating 
		{
			get
			{
				return Get("Rating");
			}
		}
		
		/// <summary>
		///   Localized string for Return to Website
		/// </summary>
		public static string ReturnToWebsite 
		{
			get
			{
				return Get("ReturnToWebsite");
			}
		}
		
		/// <summary>
		///   Localized string for Save
		/// </summary>
		public static string Save 
		{
			get
			{
				return Get("Save");
			}
		}
		
		/// <summary>
		///   Localized string for Select
		/// </summary>
		public static string Select 
		{
			get
			{
				return Get("Select");
			}
		}
		
		/// <summary>
		///   Localized string for Select a Filter
		/// </summary>
		public static string SelectAFilter 
		{
			get
			{
				return Get("SelectAFilter");
			}
		}
		
		/// <summary>
		///   Localized string for Sign In
		/// </summary>
		public static string SignIn 
		{
			get
			{
				return Get("SignIn");
			}
		}
		
		/// <summary>
		///   Localized string for Task Completed Successfully
		/// </summary>
		public static string TaskCompletedSuccessfully 
		{
			get
			{
				return Get("TaskCompletedSuccessfully");
			}
		}
		
		/// <summary>
		///   Localized string for Untitled
		/// </summary>
		public static string Untitled 
		{
			get
			{
				return Get("Untitled");
			}
		}
		
		/// <summary>
		///   Localized string for Update
		/// </summary>
		public static string Update 
		{
			get
			{
				return Get("Update");
			}
		}
		
		/// <summary>
		///   Localized string for Username
		/// </summary>
		public static string Username 
		{
			get
			{
				return Get("Username");
			}
		}
		
		/// <summary>
		///   Localized string for Verify
		/// </summary>
		public static string Verify 
		{
			get
			{
				return Get("Verify");
			}
		}
		
		/// <summary>
		///   Localized string for View
		/// </summary>
		public static string View 
		{
			get
			{
				return Get("View");
			}
		}
		
		/// <summary>
		///   Localized string for Yes
		/// </summary>
		public static string Yes 
		{
			get
			{
				return Get("Yes");
			}
		}
	}
	public class Warnings
	{
		public static string Get(string key)
		{
			return ResourceManager.GetString("Warnings", key);
		}
		
		/// <summary>
		///   Localized string for Invalid file extension.
		/// </summary>
		public static string InvalidFileExtension 
		{
			get
			{
				return Get("InvalidFileExtension");
			}
		}
	}
}