//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Frapid.i18n;
using System.Threading.Tasks;

namespace Frapid.i18n.Resources
{
	public class Titles
	{
		public static string Get(string key)
		{
			return ResourceManager.GetString("Titles", key);
		}
		
		/// <summary>
		///   Localized string for Or
		/// </summary>
		public static string Or 
		{
			get
			{
				return Get("Or");
			}
		}
		
		/// <summary>
		///   Localized string for Password
		/// </summary>
		public static string Password 
		{
			get
			{
				return Get("Password");
			}
		}
		
		/// <summary>
		///   Localized string for Return to Website
		/// </summary>
		public static string ReturnToWebsite 
		{
			get
			{
				return Get("ReturnToWebsite");
			}
		}
		
		/// <summary>
		///   Localized string for Sign In
		/// </summary>
		public static string SignIn 
		{
			get
			{
				return Get("SignIn");
			}
		}
		
		/// <summary>
		///   Localized string for Username
		/// </summary>
		public static string Username 
		{
			get
			{
				return Get("Username");
			}
		}
	}
}