#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Account;
    
    #line 1 "..\..\Views\SignUp\Index.cshtml"
    using Frapid.i18n;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SignUp/Index.cshtml")]
    public partial class _Views_SignUp_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_SignUp_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\SignUp\Index.cshtml"
  
    ViewBag.Title = "Sign Up";
    Layout = ViewBag.LayoutPath + ViewBag.Layout;
    ViewBag.Description = "Create your account on our site.";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\SignUp\Index.cshtml"
 if (CultureManager.IsRtl())
{

            
            #line default
            #line hidden
WriteLiteral("    <link");

WriteLiteral(" rel=\"Stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 232), Tuple.Create("\"", 280)
            
            #line 9 "..\..\Views\SignUp\Index.cshtml"
, Tuple.Create(Tuple.Create("", 239), Tuple.Create<System.Object, System.Int32>(Href("~/assets/css/master-page-rtl.css")
            
            #line default
            #line hidden
, 239), false)
);

WriteLiteral(" />\r\n");

            
            #line 10 "..\..\Views\SignUp\Index.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <link");

WriteLiteral(" rel=\"Stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 324), Tuple.Create("\"", 368)
            
            #line 13 "..\..\Views\SignUp\Index.cshtml"
, Tuple.Create(Tuple.Create("", 331), Tuple.Create<System.Object, System.Int32>(Href("~/assets/css/master-page.css")
            
            #line default
            #line hidden
, 331), false)
);

WriteLiteral(" />\r\n");

            
            #line 14 "..\..\Views\SignUp\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"ui attached padded signup left aligned segment\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui stackable very relaxed padded grid\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ten wide column\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui stackable form\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">Create an Account</div>\r\n                    <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"NameInputText\"");

WriteLiteral(">Your Name</label>\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"NameInputText\"");

WriteLiteral(" maxlength=\"100\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"two fields\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"PhoneInputTel\"");

WriteLiteral(">Phone Number</label>\r\n                            <input");

WriteLiteral(" id=\"PhoneInputTel\"");

WriteLiteral(" type=\"tel\"");

WriteLiteral(" required=\"\"");

WriteLiteral(">\r\n                        </div>\r\n                    </div>\r\n                  " +
"  <div");

WriteLiteral(" class=\"two fields\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"EmailInputEmail\"");

WriteLiteral(">Email Address</label>\r\n                            <input");

WriteLiteral(" type=\"email\"");

WriteLiteral(" id=\"EmailInputEmail\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" />\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"ConfirmEmailInputEmail\"");

WriteLiteral(">Confirm Email</label>\r\n                            <input");

WriteLiteral(" type=\"email\"");

WriteLiteral(" id=\"ConfirmEmailInputEmail\"");

WriteLiteral(" data-match-target=\"EmailInputEmail\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </div>\r\n                " +
"    <div");

WriteLiteral(" class=\"two fields\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"PasswordInputPassword\"");

WriteLiteral(">Password</label>\r\n                            <input");

WriteLiteral(" type=\"password\"");

WriteLiteral("\r\n                                   id=\"PasswordInputPassword\"");

WriteLiteral("\r\n                                   required=\"\"");

WriteLiteral("\r\n                                   maxlength=\"32\"");

WriteLiteral("\r\n                                   data-validation-expression=\"^(?=.*\\d)(?=.*[a" +
"-z])(?=.*[A-Z]).{6,32}$\"");

WriteLiteral("\r\n                                   data-validation-message=\"Password should con" +
"tain at least 6 characters with one uppercase, lowercase, and a number.\"");

WriteLiteral("\r\n                                   data-validation-target=\".big.error\"");

WriteLiteral("/>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"ConfirmPasswordInputPassword\"");

WriteLiteral(">Confirm Password</label>\r\n                            <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"ConfirmPasswordInputPassword\"");

WriteLiteral(" \r\n                                   data-match-target=\"PasswordInputPassword\"");

WriteLiteral(" required=\"\"");

WriteLiteral("/>\r\n                        </div>\r\n                    </div>\r\n\r\n\r\n             " +
"       <div");

WriteLiteral(" class=\"email address field\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"EmailAddressInput\"");

WriteLiteral(">Email</label>\r\n                        <input");

WriteLiteral(" type=\"email\"");

WriteLiteral(" id=\"EmailAddressInput\"");

WriteLiteral(" required=\"\"");

WriteLiteral("/>\r\n                        <div");

WriteLiteral(" class=\"ui pointing label\"");

WriteLiteral(">Please leave this field empty</div>\r\n                    </div>\r\n\r\n             " +
"       <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ui checkbox\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" id=\"AgreementCheckbox\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"AgreementCheckbox\"");

WriteLiteral(">I agree to the terms and conditions.</label>\r\n                        </div>\r\n  " +
"                  </div>\r\n                    <div");

WriteLiteral(" class=\"big error vpad8\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"ui blue button\"");

WriteLiteral(" id=\"SignUpButton\"");

WriteLiteral(">Sign Me Up</div>\r\n                    <a");

WriteLiteral(" class=\"ui negative button\"");

WriteLiteral(" href=\"/\"");

WriteLiteral(">Cancel</a>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"six wide column\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui positive message\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"ui header\"");

WriteLiteral(">Please Note</div>\r\n                    <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n                    We use cookies in our website.\r\n                    " +
"Please read the <a");

WriteLiteral(" href=\"/site/legal/terms-of-use\"");

WriteLiteral(">terms of use</a>\r\n                    before you create an account.\r\n           " +
"     </div>\r\n            </div>\r\n        </div>\r\n\r\n    </div>\r\n</div>\r\n\r\n<script" +
"");

WriteLiteral(" src=\"/i18n/resources.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/core/frapid-ajax.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/core/validation.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/validator.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Areas/Frapid.Account/Scripts/Account/SignUp/signup.js\"");

WriteLiteral("></script>\r\n");

        }
    }
}
#pragma warning restore 1591
