#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Frapid.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Configuration/Index.cshtml")]
    public partial class _Views_Configuration_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Configuration_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Configuration\Index.cshtml"
  
    ViewBag.Title = "Configure Website";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral(@"

<script>
    var scrudFactory = new Object();

    scrudFactory.title = ""Configure Website"";

    scrudFactory.viewAPI = ""/api/forms/website/configurations"";
    scrudFactory.viewTableName = ""website.configurations"";

    scrudFactory.formAPI = ""/api/forms/website/configurations"";
    scrudFactory.formTableName = ""website.configurations"";

    scrudFactory.excludedColumns = [""audit_user_id"", ""audit_ts""];

    scrudFactory.allowDelete = true;
    scrudFactory.allowEdit = true;

    scrudFactory.live = ""WebsiteName"";

    scrudFactory.layout = [
        {
            tab: """",
            fields: [
                [""ConfigurationId""],
                [""DomainName"", ""WebsiteName""],
                [""IsDefault"", """"],
                [""Description""],
                [""BlogTitle"", """"],
                [""BlogDescription""]
            ]
        }
    ];

    scrudFactory.card = {
        header: ""website_name"",
        meta: ""domain_name"",
        description: ""blog_title""
    };

    $.get('/ScrudFactory/View.html', function(view) {
        $.get('/ScrudFactory/Form.html', function(form) {

            $(""#ScrudFactoryView"").html(view);
            $(""#ScrudFactoryForm"").html(form);
            setTimeout(function() {
                $.cachedScript(""/assets/js/scrudfactory-view.js"");
                $.cachedScript(""/assets/js/scrudfactory-form.js"");
            }, 100);
        });
    });
</script>

<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>\r\n");

        }
    }
}
#pragma warning restore 1591
