#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Account;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ConfigurationProfile/Index.cshtml")]
    public partial class _Views_ConfigurationProfile_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_ConfigurationProfile_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\ConfigurationProfile\Index.cshtml"
  
    ViewBag.Title = "Configuration Profiles";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"Con" +
"figuration Profiles\";\r\n\r\n    scrudFactory.viewAPI = \"/api/views/account/configur" +
"ation-profile-scrud-view\";\r\n    scrudFactory.viewTableName = \"account.configurat" +
"ion_profile_scrud_view\";\r\n\r\n    scrudFactory.formAPI = \"/api/forms/account/confi" +
"guration-profiles\";\r\n    scrudFactory.formTableName = \"account.configuration_pro" +
"files\";\r\n\r\n    scrudFactory.excludedColumns = [\"audit_user_id\", \"audit_ts\"];\r\n\r\n" +
"    scrudFactory.allowDelete = true;\r\n    scrudFactory.allowEdit = true;\r\n\r\n    " +
"scrudFactory.live = \"ProfileName\";\r\n\r\n    scrudFactory.card = {\r\n        header:" +
" \"profile_name\",\r\n        meta: \"defult_role\",\r\n        description: \"default_of" +
"fice\"\r\n    };\r\n\r\n    scrudFactory.keys = [\r\n        {\r\n            property: \"Re" +
"gistrationOfficeId\",\r\n            url: \'/api/forms/core/offices/display-fields\'," +
"\r\n            data: null,\r\n            valueField: \"Key\",\r\n            textField" +
": \"Value\"\r\n        },\r\n        {\r\n            property: \"RegistrationRoleId\",\r\n " +
"           url: \'/api/forms/account/roles/display-fields\',\r\n            data: nu" +
"ll,\r\n            valueField: \"Key\",\r\n            textField: \"Value\"\r\n        }\r\n" +
"    ];\r\n\r\n    $.get(\'/ScrudFactory/View.html\', function (view) {\r\n        $.get(" +
"\'/ScrudFactory/Form.html\', function (form) {\r\n            $(\"#ScrudFactoryView\")" +
".html(view);\r\n            $(\"#ScrudFactoryForm\").html(form);\r\n            $.cach" +
"edScript(\"/assets/js/scrudfactory-view.js\");\r\n            $.cachedScript(\"/asset" +
"s/js/scrudfactory-form.js\");\r\n        });\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
