#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Frapid.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MenuItem/Index.cshtml")]
    public partial class _Views_MenuItem_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_MenuItem_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\MenuItem\Index.cshtml"
  
    ViewBag.Title = "Menu Items";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"M" +
"enu Items\";\r\n\r\n    scrudFactory.viewAPI = \"/api/forms/website/menu-items\";\r\n    " +
"scrudFactory.viewTableName = \"website.menu_items\";\r\n\r\n    scrudFactory.formAPI =" +
" \"/api/forms/website/menu-items\";\r\n    scrudFactory.formTableName = \"website.men" +
"u_items\";\r\n\r\n    scrudFactory.excludedColumns = [\"audit_user_id\", \"audit_ts\"];\r\n" +
"\r\n    scrudFactory.allowDelete = true;\r\n    scrudFactory.allowEdit = true;\r\n\r\n  " +
"  scrudFactory.live = \"Title\";\r\n\r\n    scrudFactory.layout = [\r\n        {\r\n      " +
"      tab: \"\",\r\n            fields: [\r\n                [\"MenuItemId\", \"\"],\r\n    " +
"            [\"MenuId\", \"Title\"],\r\n                [\"ContentId\", \"\"],\r\n          " +
"      [\"Url\", \"Sort\"]\r\n            ]\r\n        }\r\n    ];\r\n\r\n    scrudFactory.card" +
" = {\r\n        header: \"title\",\r\n        description: \"url\"\r\n    };\r\n\r\n    scrudF" +
"actory.back = {\r\n        Title: \"Back to Menus\",\r\n        Url: \"/dashboard/websi" +
"te/menus\"\r\n    };\r\n\r\n    scrudFactory.keys = [\r\n        {\r\n            property:" +
" \"MenuId\",\r\n            url: \'/api/forms/website/menus/display-fields\',\r\n       " +
"     data: null,\r\n            valueField: \"Key\",\r\n            textField: \"Value\"" +
"\r\n        },\r\n        {\r\n            property: \"ParentMenuItemId\",\r\n            " +
"url: \'/api/forms/website/menu-items/all\',\r\n            data: null,\r\n            " +
"valueField: \"menu_item_id\",\r\n            textField: \"title\"\r\n        },\r\n       " +
" {\r\n            property: \"ContentId\",\r\n            url: \'/api/forms/website/con" +
"tents/all\',\r\n            data: null,\r\n            valueField: \"content_id\",\r\n   " +
"         textField: \"title\"\r\n        }\r\n    ];\r\n\r\n    $.get(\'/ScrudFactory/View." +
"html\', function (view) {\r\n        $.get(\'/ScrudFactory/Form.html\', function (for" +
"m) {\r\n            $(\"#ScrudFactoryView\").html(view);\r\n            $(\"#ScrudFacto" +
"ryForm\").html(form);\r\n            $.cachedScript(\"/assets/js/scrudfactory-view.j" +
"s\");\r\n            $.cachedScript(\"/assets/js/scrudfactory-form.js\");\r\n        })" +
";\r\n    });\r\n</script>\r\n<script>\r\n    $(document).on(\"formready\", function () {\r\n" +
"        $(\"#category_name\").keyup(function () {\r\n            function getAlias(t" +
"itle) {\r\n                return title.toLowerCase().replace(/ +(?= )/g, \'\').repl" +
"ace(/ /g, \'-\').replace(/[^\\w-]+/g, \'\');\r\n            };\r\n\r\n            var categ" +
"ory = $(this).val();\r\n            var alias = getAlias(category);\r\n\r\n           " +
" $(\"#alias\").val(alias);\r\n\r\n        });\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
