#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Account;
    
    #line 3 "..\..\Views\SignIn\Index.cshtml"
    using Frapid.Areas;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\SignIn\Index.cshtml"
    using Frapid.i18n;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\SignIn\Index.cshtml"
    using Frapid.i18n.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SignIn/Index.cshtml")]
    public partial class _Views_SignIn_Index_cshtml : System.Web.Mvc.WebViewPage<Frapid.Account.ViewModels.SignIn>
    {
        public _Views_SignIn_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\"" +
"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"Frapid Framework\"");

WriteLiteral(" />\r\n    <!-- <link href=\"https://fonts.googleapis.com/css?family=Titillium+Web\" " +
"rel=\"stylesheet\" type=\"text/css\" /> -->\r\n    <title>\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\SignIn\Index.cshtml"
   Write(Titles.SignIn);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </title>\r\n");

            
            #line 16 "..\..\Views\SignIn\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\SignIn\Index.cshtml"
     if (CultureManager.IsRtl())
    {


            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteLiteral(" rel=\"Stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 627), Tuple.Create("\"", 675)
            
            #line 19 "..\..\Views\SignIn\Index.cshtml"
, Tuple.Create(Tuple.Create("", 634), Tuple.Create<System.Object, System.Int32>(Href("~/assets/css/master-page-rtl.css")
            
            #line default
            #line hidden
, 634), false)
);

WriteLiteral(" />\r\n");

            
            #line 20 "..\..\Views\SignIn\Index.cshtml"
    }
    else
    {


            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteLiteral(" rel=\"Stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 737), Tuple.Create("\"", 781)
            
            #line 24 "..\..\Views\SignIn\Index.cshtml"
, Tuple.Create(Tuple.Create("", 744), Tuple.Create<System.Object, System.Int32>(Href("~/assets/css/master-page.css")
            
            #line default
            #line hidden
, 744), false)
);

WriteLiteral(" />\r\n");

            
            #line 25 "..\..\Views\SignIn\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 27 "..\..\Views\SignIn\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\SignIn\Index.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.GoogleSigninClientId))
    {

            
            #line default
            #line hidden
WriteLiteral("    <!-- Google Sign In -->\r\n");

WriteLiteral("        <meta");

WriteLiteral(" name=\"google-signin-scope\"");

WriteAttribute("content", Tuple.Create(" content=\"", 938), Tuple.Create("\"", 972)
            
            #line 30 "..\..\Views\SignIn\Index.cshtml"
, Tuple.Create(Tuple.Create("", 948), Tuple.Create<System.Object, System.Int32>(Model.GoogleSignInScope
            
            #line default
            #line hidden
, 948), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        <meta");

WriteLiteral(" name=\"google-signin-client_id\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1020), Tuple.Create("\"", 1057)
            
            #line 31 "..\..\Views\SignIn\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1030), Tuple.Create<System.Object, System.Int32>(Model.GoogleSigninClientId
            
            #line default
            #line hidden
, 1030), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        <script");

WriteLiteral(" src=\"https://apis.google.com/js/platform.js\"");

WriteLiteral(" async defer></script>\r\n");

            
            #line 33 "..\..\Views\SignIn\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/i18n/resources.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/assets/js/backend.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Scripts/jssha1.5/src/sha.js\"");

WriteLiteral("></script>\r\n</head>\r\n<body");

WriteLiteral(" id=\"SignInBody\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"signin-form\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui attached stackable padded segment\"");

WriteLiteral(" id=\"SignInSegment\"");

WriteLiteral(">\r\n            <img");

WriteLiteral(" class=\"ui small image\"");

WriteLiteral(" src=\"/Static/images/logo.png\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui big error large dividing header vpad8\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"ui toggle checkbox vpad8\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"SocialLoginCheckbox\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"SocialLoginCheckbox\"");

WriteLiteral(">Social Login</label>\r\n            </div>\r\n            <form");

WriteLiteral(" class=\"ui stackable login form\"");

WriteLiteral(" id=\"LoginForm\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"EmailInputEmail\"");

WriteLiteral(">Email Address</label>\r\n                    <div");

WriteLiteral(" class=\"ui left icon input\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"user icon\"");

WriteLiteral("></i>\r\n                        <input");

WriteLiteral(" id=\"EmailInputEmail\"");

WriteLiteral(" placeholder=\"Email\"");

WriteLiteral("\r\n                               autocapitalize=\"off\"");

WriteLiteral(" autocorrect=\"off\"");

WriteLiteral(" type=\"email\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"PasswordInputPassword\"");

WriteLiteral(">Password</label>\r\n                    <div");

WriteLiteral(" class=\"ui left icon input\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"lock icon\"");

WriteLiteral("></i>\r\n                        <input");

WriteLiteral(" id=\"PasswordInputPassword\"");

WriteLiteral(" placeholder=\"Password\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"OfficeIdSelect\"");

WriteLiteral(">Select Office</label>\r\n                    <select");

WriteLiteral(" class=\"ui search office dropdown\"");

WriteLiteral(" id=\"OfficeIdSelect\"");

WriteLiteral(" required=\"\"");

WriteLiteral("></select>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"CultureSelect\"");

WriteLiteral(">Select Language</label>\r\n                    <select");

WriteLiteral(" class=\"ui search language dropdown\"");

WriteLiteral(" id=\"CultureSelect\"");

WriteLiteral(" required=\"\"");

WriteLiteral("></select>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"ChallengeInputHidden\"");

WriteAttribute("value", Tuple.Create("\r\n                           value=\"", 3270), Tuple.Create("\"", 3322)
            
            #line 74 "..\..\Views\SignIn\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3306), Tuple.Create<System.Object, System.Int32>(Model.Challenge
            
            #line default
            #line hidden
, 3306), false)
);

WriteLiteral(" />\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"ui buttons\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" id=\"SignInButton\"");

WriteLiteral(" title=\"CRTL + RETURN\"");

WriteLiteral(" class=\"ui grey button\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">\r\n                        Sign In\r\n                    </button>\r\n              " +
"      <a");

WriteLiteral(" class=\"ui button\"");

WriteLiteral(" href=\"/\"");

WriteLiteral(">Cancel</a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"exception field\"");

WriteLiteral("></div>\r\n            </form>\r\n            <div");

WriteLiteral(" id=\"SocialLoginForm\"");

WriteLiteral(" class=\"ui login form\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"SocialOfficeSelect\"");

WriteLiteral(">Select Office</label>\r\n                    <select");

WriteLiteral(" class=\"ui search office dropdown\"");

WriteLiteral(" id=\"SocialOfficeSelect\"");

WriteLiteral("></select>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"SocialLanguageSelect\"");

WriteLiteral(">Select Language</label>\r\n                    <select");

WriteLiteral(" class=\"ui search language dropdown\"");

WriteLiteral(" id=\"SocialLanguageSelect\"");

WriteLiteral("></select>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"g-signin2\"");

WriteLiteral(" data-onsuccess=\"onSignIn\"");

WriteLiteral(" data-theme=\"dark\"");

WriteLiteral("\r\n                     data-width=\"134px\"");

WriteLiteral(" data-height=\"32\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"tpad8\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"ui facebook fluid button\"");

WriteLiteral(" id=\"FacebookButton\"");

WriteLiteral(" style=\"width: 134px;\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"facebook icon\"");

WriteLiteral("></i>Facebook\r\n\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"ui breadcrumb vpad8\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"section\"");

WriteLiteral(" href=\"/account/sign-up\"");

WriteLiteral(">Create an Account</a>\r\n                <div");

WriteLiteral(" class=\"divider\"");

WriteLiteral("> / </div>\r\n                <a");

WriteLiteral(" class=\"section\"");

WriteLiteral(" href=\"/account/reset\"");

WriteLiteral(">Reset My Password</a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 108 "..\..\Views\SignIn\Index.cshtml"
Write(Html.GetAntiForgeryToken(this.Request.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script>\r\n        var fbAppId = \'");

            
            #line 110 "..\..\Views\SignIn\Index.cshtml"
                  Write(Model.FacebookAppId);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var fbScope = \'");

            
            #line 111 "..\..\Views\SignIn\Index.cshtml"
                  Write(Model.FacebookScope);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        localStorage.removeItem(\"haveWeMet\");\r\n    </script>\r\n    <div");

WriteLiteral(" id=\"fb-root\"");

WriteLiteral("></div>\r\n    <script");

WriteLiteral(" src=\"/Areas/Frapid.Account/Scripts/Account/SignIn/default.js\"");

WriteLiteral("></script>\r\n\r\n");

            
            #line 117 "..\..\Views\SignIn\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 117 "..\..\Views\SignIn\Index.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.FacebookAppId))
    {

            
            #line default
            #line hidden
WriteLiteral("    <!-- Facebook Sign In -->\r\n");

WriteLiteral("        <script");

WriteLiteral(" src=\"/Areas/Frapid.Account/Scripts/Account/SignIn/facebook.js\"");

WriteLiteral("></script>\r\n");

            
            #line 121 "..\..\Views\SignIn\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 123 "..\..\Views\SignIn\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\SignIn\Index.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.GoogleSigninClientId))
    {

            
            #line default
            #line hidden
WriteLiteral("    <!-- Google Sign In -->\r\n");

WriteLiteral("        <script");

WriteLiteral(" src=\"/Areas/Frapid.Account/Scripts/Account/SignIn/google.js\"");

WriteLiteral("></script>\r\n");

            
            #line 127 "..\..\Views\SignIn\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
