#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Frapid.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Layout/Shared/DeleteThemeModal.cshtml")]
    public partial class _Views_Layout_Shared_DeleteThemeModal_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Layout_Shared_DeleteThemeModal_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"ui small modal\"");

WriteLiteral(" id=\"DeleteThemeModal\"");

WriteLiteral(">\r\n    <i");

WriteLiteral(" class=\"close icon\"");

WriteLiteral("></i>\r\n    <div");

WriteLiteral(" class=\"ui red large header\"");

WriteLiteral(">\r\n        Proceed with Caution!\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui large header\"");

WriteLiteral(">Are you sure you want to delete the \"<span");

WriteLiteral(" class=\"theme name text\"");

WriteLiteral("></span>\" theme?</div>\r\n        <p>\r\n            You are about to delete the sele" +
"cted theme.            \r\n            Doing this will permanently delete the them" +
"e and associated files.\r\n        </p>\r\n\r\n        <div");

WriteLiteral(" class=\"ui negative message\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui small exception header\"");

WriteLiteral(">Cannot delete this theme because of xyz.</div>\r\n        </div>\r\n\r\n    </div>\r\n  " +
"  <div");

WriteLiteral(" class=\"ui content attached segment\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui buttons\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(" onclick=\"showDeleteThemeModal();\"");

WriteLiteral(">\r\n                No, Don\'t Delete This Theme\r\n            </div>\r\n            <" +
"div");

WriteLiteral(" class=\"ui red button\"");

WriteLiteral(" id=\"DeleteThemeButton\"");

WriteLiteral(">\r\n                Yes\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
