#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Frapid.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Layout/Shared/NewThemeModal.cshtml")]
    public partial class _Views_Layout_Shared_NewThemeModal_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Layout_Shared_NewThemeModal_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"ui modal\"");

WriteLiteral(" id=\"NewThemeModal\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"header\"");

WriteLiteral(">\r\n        Add a New Theme\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui basic segment\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui two column very relaxed stackable grid\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"eight wide center aligned column\"");

WriteLiteral(">\r\n\r\n                    <i");

WriteLiteral(" class=\"massive cloud upload green icon\"");

WriteLiteral("></i>\r\n                    <div");

WriteLiteral(" class=\"vpad8\"");

WriteLiteral("></div>\r\n\r\n                    <div");

WriteLiteral(" class=\"ui big header\"");

WriteLiteral(">\r\n                        Upload a Theme\r\n                    </div>\r\n\r\n        " +
"            <div");

WriteLiteral(" class=\"vpad8\"");

WriteLiteral("></div>\r\n\r\n\r\n                    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"UploadThemeInputFile\"");

WriteLiteral(" class=\"ui basic green button\"");

WriteLiteral(">From Local Hard Drive</label>\r\n                        <input");

WriteLiteral(" id=\"UploadThemeInputFile\"");

WriteLiteral("\r\n                               data-handler=\"/dashboard/my/website/themes/uploa" +
"d\"");

WriteLiteral("\r\n                               data-loader-id=\"UploaderSegment\"");

WriteLiteral("\r\n                               class=\"file\"");

WriteLiteral("\r\n                               style=\"display: none\"");

WriteLiteral("\r\n                               type=\"file\"");

WriteLiteral(">\r\n                    </div>\r\n\r\n                    <div");

WriteLiteral(" class=\"vpad16\"");

WriteLiteral("></div>\r\n\r\n                    <div");

WriteLiteral(" class=\"ui horizontal divider\"");

WriteLiteral(">OR</div>\r\n\r\n                    <div");

WriteLiteral(" class=\"vpad16\"");

WriteLiteral("></div>\r\n\r\n                    <div");

WriteLiteral(" class=\"ui small header\"");

WriteLiteral(">Download Theme From</div>\r\n                    <div");

WriteLiteral(" class=\"ui fluid labeled input\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ui basic label\"");

WriteLiteral(">Url</div>\r\n                        <input");

WriteLiteral(" id=\"RemoteUploadUrl\"");

WriteLiteral(" type=\"url\"");

WriteLiteral(" value=\"http://\"");

WriteLiteral(">\r\n                    </div>\r\n\r\n                    <div");

WriteLiteral(" class=\"vpad8\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"ui left aligned basic green button\"");

WriteLiteral(" onclick=\"remoteUpload();\"");

WriteLiteral(">Download and Install</button>\r\n                    </div>\r\n\r\n                   " +
" <div");

WriteLiteral(" class=\"ui error padded message\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ui small header\"");

WriteLiteral("></div>\r\n                    </div>\r\n                </div>\r\n\r\n                <d" +
"iv");

WriteLiteral(" class=\"ui vertical divider\"");

WriteLiteral(">\r\n                    OR\r\n                </div>\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"eight wide column\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"ui big header\"");

WriteLiteral(">\r\n                        Create a Brand New Theme\r\n                    </div>\r\n" +
"                    <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n                    <form");

WriteLiteral(" class=\"ui padded form\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>Theme Name</label>\r\n                       " +
"     <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"ThemeName\"");

WriteLiteral(" required=\"\"");

WriteLiteral("/>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>Author</label>\r\n                           " +
" <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"Author\"");

WriteLiteral(" required=\"\"");

WriteLiteral("/>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>Author Url</label>\r\n                       " +
"     <input");

WriteLiteral(" type=\"url\"");

WriteLiteral(" name=\"AuthorUrl\"");

WriteLiteral("/>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>Author Email</label>\r\n                     " +
"       <input");

WriteLiteral(" type=\"email\"");

WriteLiteral(" name=\"AuthorEmail\"");

WriteLiteral(" required=\"\"");

WriteLiteral("/>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>Theme Converted By</label>\r\n               " +
"             <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"ConvertedBy\"");

WriteLiteral("\r\n                                   title=\"If this theme was ported from another" +
" platform, enter the name of the person or company who converted this theme to f" +
"rapid.\"");

WriteLiteral("/>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>Released On</label>\r\n                      " +
"      <input");

WriteLiteral(" type=\"date\"");

WriteLiteral(" name=\"ReleasedOn\"");

WriteLiteral("/>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>Theme Version</label>\r\n                    " +
"        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"Version\"");

WriteLiteral("/>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>Category</label>\r\n                         " +
"   <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"Category\"");

WriteLiteral("/>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>Responsive</label>\r\n                       " +
"     <div");

WriteLiteral(" class=\"ui toggle checkbox vpad8\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" name=\"Responsive\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" checked=\"checked\"");

WriteLiteral(">\r\n                                <label>&nbsp;</label>\r\n                       " +
"     </div>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>CSS Framework</label>\r\n                    " +
"        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"Framework\"");

WriteLiteral("/>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>Tags</label>\r\n                            <" +
"input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"Tags\"");

WriteLiteral(" title=\"Comma separated list of tags.\"");

WriteLiteral("/>\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"ui buttons\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" class=\"ui positive button\"");

WriteLiteral(" onclick=\"createTheme();\"");

WriteLiteral(">Let\'s Go!</button>\r\n                            <button");

WriteLiteral(" class=\"ui negative button\"");

WriteLiteral(" onclick=\'$(\"#NewThemeModal\").modal(\"hide\");\'");

WriteLiteral(">Cancel</button>\r\n                        </div>\r\n                    </form>\r\n\r\n" +
"                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
