#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Account;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmailTemplate/Index.cshtml")]
    public partial class _Views_EmailTemplate_Index_cshtml : System.Web.Mvc.WebViewPage<Frapid.Account.ViewModels.Template>
    {
        public _Views_EmailTemplate_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\EmailTemplate\Index.cshtml"
  
    ViewBag.Title = Model.Title;
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<link");

WriteLiteral(" href=\"/my/template/css/site.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n<style>\r\n    #editor {\r\n        position: absolute;\r\n        top: 0px;\r\n      " +
"  right: 0;\r\n        bottom: 0;\r\n        left: 0;\r\n    }\r\n</style>\r\n\r\n<script");

WriteLiteral(" src=\"/Scripts/ace-1.2.2/src-min-noconflict/ace.js\"");

WriteLiteral("></script>\r\n\r\n<script>\r\n    var saveUrl = \"/dashboard/website/subscription/remove" +
"d/save\";\r\n</script>\r\n\r\n<div");

WriteLiteral(" class=\"ui stackable divided grid\"");

WriteLiteral(" style=\"height: 100%;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui three wide column segment\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui header\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 27 "..\..\Views\EmailTemplate\Index.cshtml"
       Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ui basic buttons\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(" id=\"SaveButton\"");

WriteLiteral(">Save</div>\r\n            <a");

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(" href=\"javascript:history.go(-1)\"");

WriteLiteral(">Back</a>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"thirteen wide column\"");

WriteLiteral(" data-target=\"editor\"");

WriteLiteral(" style=\"height: 100%;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"editor\"");

WriteLiteral(">\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<script>\r\n    var title = \"");

            
            #line 42 "..\..\Views\EmailTemplate\Index.cshtml"
            Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n    var html = \"");

            
            #line 43 "..\..\Views\EmailTemplate\Index.cshtml"
           Write(Html.Encode(HttpUtility.JavaScriptStringEncode(Model.Contents)));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n</script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1186), Tuple.Create("\"", 1246)
, Tuple.Create(Tuple.Create("", 1192), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Frapid.Account/Scripts/EmailTemplate/Editor.js")
, 1192), false)
);

WriteLiteral("></script>");

        }
    }
}
#pragma warning restore 1591
