#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Account;
    
    #line 3 "..\..\Views\SignOut\Index.cshtml"
    using Frapid.Areas;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\SignOut\Index.cshtml"
    using Frapid.i18n;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\SignOut\Index.cshtml"
    using Frapid.i18n.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SignOut/Index.cshtml")]
    public partial class _Views_SignOut_Index_cshtml : System.Web.Mvc.WebViewPage<Frapid.Account.ViewModels.SignIn>
    {
        public _Views_SignOut_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\"" +
"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"Frapid Framework\"");

WriteLiteral(" />\r\n    <script");

WriteLiteral(" src=\"/i18n/resources.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/assets/js/backend.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Scripts/jssha1.5/src/sha.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/validator.js\"");

WriteLiteral("></script>\r\n    <title>\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\SignOut\Index.cshtml"
   Write(Titles.SignIn);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </title>\r\n</head>\r\n<body>\r\nPlease wait\r\n\r\n<script>\r\n    localStorage.remove" +
"Item(\"access_token\");\r\n    document.location = \"/account/sign-in\";\r\n</script>\r\n<" +
"/body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
