#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Frapid.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ContactUs/ContactForm.cshtml")]
    public partial class _Views_ContactUs_ContactForm_cshtml : System.Web.Mvc.WebViewPage<Frapid.WebsiteBuilder.ViewModels.ContactForm>
    {
        public _Views_ContactUs_ContactForm_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"ui contact form\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"big error\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n        <label>\r\n            Your Name\r\n        </label>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"NameInputText\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n        <label>\r\n            Email\r\n        </label>\r\n        <input");

WriteLiteral(" type=\"email\"");

WriteLiteral(" name=\"EmailInputEmail\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n        <label>\r\n            Subject\r\n        </label>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"SubjectInputText\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"phone number field\"");

WriteLiteral(">\r\n        <label>\r\n            Phone\r\n        </label>\r\n        <input");

WriteLiteral(" type=\"tel\"");

WriteLiteral(" name=\"PhoneInputTel\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" value=\"\"");

WriteLiteral("/>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n        <label>\r\n            Message\r\n        </label>\r\n        <textarea");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"MessageTextArea\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" maxlength=\"1000\"");

WriteLiteral("></textarea>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"hidden field\"");

WriteLiteral(">\r\n        <label>&nbsp;</label>\r\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"ContactIdInputHidden\"");

WriteLiteral(" required=\"\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1114), Tuple.Create("\"", 1138)
            
            #line 36 "..\..\Views\ContactUs\ContactForm.cshtml"
, Tuple.Create(Tuple.Create("", 1122), Tuple.Create<System.Object, System.Int32>(Model.ContactId
            
            #line default
            #line hidden
, 1122), false)
);

WriteLiteral(" />\r\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"TokenInputHidden\"");

WriteLiteral(" required=\"\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1208), Tuple.Create("\"", 1230)
            
            #line 37 "..\..\Views\ContactUs\ContactForm.cshtml"
, Tuple.Create(Tuple.Create("", 1216), Tuple.Create<System.Object, System.Int32>(ViewBag.Token
            
            #line default
            #line hidden
, 1216), false)
);

WriteLiteral(" />\r\n    </div>\r\n    <button");

WriteLiteral(" class=\"ui teal send email button\"");

WriteLiteral(" onclick=\"sendEmail(this)\"");

WriteLiteral(">Send Email</button>\r\n</div>\r\n\r\n\r\n<script");

WriteLiteral(" src=\"/i18n/resources.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/assets/js/backend.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Scripts/jssha1.5/src/sha.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/validator.js\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1628), Tuple.Create("\"", 1696)
, Tuple.Create(Tuple.Create("", 1634), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Frapid.WebsiteBuilder/Scripts/ContactUs/ContactForm.js")
, 1634), false)
);

WriteLiteral("></script>");

        }
    }
}
#pragma warning restore 1591
