#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Frapid.Web;
    
    #line 1 "..\..\Views\ContactUs\Index.cshtml"
    using Frapid.WebsiteBuilder.ViewModels;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ContactUs/Index.cshtml")]
    public partial class _Views_ContactUs_Index_cshtml : System.Web.Mvc.WebViewPage<Frapid.WebsiteBuilder.ViewModels.ContactUs>
    {
        public _Views_ContactUs_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\ContactUs\Index.cshtml"
  
    ViewBag.Title = "Contact Us";
    Layout = ViewBag.LayoutPath + ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/assets/css/master-page.css\"");

WriteLiteral(" />\r\n\r\n<div");

WriteLiteral(" id=\"section\"");

WriteLiteral(" class=\"ui basic padded signup left aligned segment\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui grey huge header\"");

WriteLiteral(">Contact Us</div>\r\n        <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"ui two column stackable grid\"");

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Views\ContactUs\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\ContactUs\Index.cshtml"
             foreach (var item in Model.Contacts)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"column\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"ui teal big header\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 19 "..\..\Views\ContactUs\Index.cshtml"
                   Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 21 "..\..\Views\ContactUs\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\ContactUs\Index.cshtml"
                         if (!string.IsNullOrWhiteSpace(item.Name))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"sub header\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 24 "..\..\Views\ContactUs\Index.cshtml"
                           Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");

            
            #line 26 "..\..\Views\ContactUs\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                    <div>\r\n");

            
            #line 29 "..\..\Views\ContactUs\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\ContactUs\Index.cshtml"
                         if (!string.IsNullOrWhiteSpace(item.Position))
                        {
                            
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\ContactUs\Index.cshtml"
                       Write(item.Position);

            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\ContactUs\Index.cshtml"
                                          
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 33 "..\..\Views\ContactUs\Index.cshtml"
                         if (!string.IsNullOrWhiteSpace(item.Address))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <br />\r\n");

            
            #line 36 "..\..\Views\ContactUs\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\ContactUs\Index.cshtml"
                       Write(item.Address);

            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\ContactUs\Index.cshtml"
                                         
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 39 "..\..\Views\ContactUs\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\ContactUs\Index.cshtml"
                         if (!string.IsNullOrWhiteSpace(item.City))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <br />\r\n");

            
            #line 42 "..\..\Views\ContactUs\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\ContactUs\Index.cshtml"
                       Write(item.City);

            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\ContactUs\Index.cshtml"
                                      
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 44 "..\..\Views\ContactUs\Index.cshtml"
                         if (!string.IsNullOrWhiteSpace(item.State))
                        {
                            
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\ContactUs\Index.cshtml"
                       Write(item.State);

            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\ContactUs\Index.cshtml"
                                       
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 48 "..\..\Views\ContactUs\Index.cshtml"
                         if (!string.IsNullOrWhiteSpace(item.Country))
                        {
                            
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\ContactUs\Index.cshtml"
                       Write(item.Country);

            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\ContactUs\Index.cshtml"
                                         
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 52 "..\..\Views\ContactUs\Index.cshtml"
                         if (!string.IsNullOrWhiteSpace(item.PostalCode))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <br />");

WriteLiteral("<em>Postal Code:</em>\r\n");

            
            #line 55 "..\..\Views\ContactUs\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\ContactUs\Index.cshtml"
                       Write(item.PostalCode);

            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\ContactUs\Index.cshtml"
                                            
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <br />\r\n                        <br />\r\n\r\n");

            
            #line 60 "..\..\Views\ContactUs\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\ContactUs\Index.cshtml"
                         if (!string.IsNullOrWhiteSpace(item.Telephone))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <strong>Telephone:</strong>\r\n");

            
            #line 63 "..\..\Views\ContactUs\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\ContactUs\Index.cshtml"
                       Write(item.Telephone);

            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\ContactUs\Index.cshtml"
                                           
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 65 "..\..\Views\ContactUs\Index.cshtml"
                         if (!string.IsNullOrWhiteSpace(item.PostalCode))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <br />");

WriteLiteral("<strong>Postal Code:</strong>\r\n");

            
            #line 68 "..\..\Views\ContactUs\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 68 "..\..\Views\ContactUs\Index.cshtml"
                       Write(item.PostalCode);

            
            #line default
            #line hidden
            
            #line 68 "..\..\Views\ContactUs\Index.cshtml"
                                            
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 70 "..\..\Views\ContactUs\Index.cshtml"
                         if (!string.IsNullOrWhiteSpace(item.Email) && item.DisplayEmail)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <br />");

WriteLiteral("<strong>Email:</strong>\r\n");

WriteLiteral("                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2902), Tuple.Create("\"", 2927)
, Tuple.Create(Tuple.Create("", 2909), Tuple.Create("mailto:", 2909), true)
            
            #line 73 "..\..\Views\ContactUs\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2916), Tuple.Create<System.Object, System.Int32>(item.Email
            
            #line default
            #line hidden
, 2916), false)
);

WriteLiteral(">");

            
            #line 73 "..\..\Views\ContactUs\Index.cshtml"
                                                    Write(item.Email);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 74 "..\..\Views\ContactUs\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 75 "..\..\Views\ContactUs\Index.cshtml"
                         if (!string.IsNullOrWhiteSpace(item.Details))
                        {
                            
            
            #line default
            #line hidden
            
            #line 77 "..\..\Views\ContactUs\Index.cshtml"
                       Write(Html.Raw(item.Details));

            
            #line default
            #line hidden
            
            #line 77 "..\..\Views\ContactUs\Index.cshtml"
                                                   
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n\r\n");

            
            #line 81 "..\..\Views\ContactUs\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 81 "..\..\Views\ContactUs\Index.cshtml"
                     if (item.DisplayContactForm && !string.IsNullOrWhiteSpace(item.Email))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <br />\r\n");

WriteLiteral("                        <button");

WriteLiteral(" class=\"ui teal button\"");

WriteLiteral(" onclick=\"showContactForm(this)\"");

WriteLiteral(">Send Email</button>\r\n");

            
            #line 85 "..\..\Views\ContactUs\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 85 "..\..\Views\ContactUs\Index.cshtml"
                   Write(Html.Partial("~/Areas/Frapid.WebsiteBuilder/Views/ContactUs/ContactForm.cshtml", new ContactForm { ContactId = item.ContactId }));

            
            #line default
            #line hidden
            
            #line 85 "..\..\Views\ContactUs\Index.cshtml"
                                                                                                                                                         
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 89 "..\..\Views\ContactUs\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n\r\n<script>\r\n    function showContactForm(el) " +
"{\r\n        el = $(el);\r\n        el.siblings(\".ui.contact.form\").slideDown(200);\r" +
"\n        el.remove();\r\n    };\r\n</script>");

        }
    }
}
#pragma warning restore 1591
