#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Frapid.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Category/Index.cshtml")]
    public partial class _Views_Category_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Category_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Category\Index.cshtml"
  
    ViewBag.Title = "Content Categories";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"C" +
"ontent Categories\";\r\n\r\n    scrudFactory.viewAPI = \"/api/forms/website/categories" +
"\";\r\n    scrudFactory.viewTableName = \"website.categories\";\r\n\r\n    scrudFactory.f" +
"ormAPI = \"/api/forms/website/categories\";\r\n    scrudFactory.formTableName = \"web" +
"site.categories\";\r\n\r\n    scrudFactory.excludedColumns = [\"audit_user_id\", \"audit" +
"_ts\"];\r\n\r\n    scrudFactory.allowDelete = true;\r\n    scrudFactory.allowEdit = tru" +
"e;\r\n\r\n    scrudFactory.live = \"CategoryName\";\r\n\r\n    scrudFactory.layout = [\r\n  " +
"      {\r\n            tab: \"\",\r\n            fields: [\r\n                [\"Category" +
"Id\", \"\"],\r\n                [\"CategoryName\", \"Alias\"],\r\n                [\"SeoDesc" +
"ription\"]\r\n            ]\r\n        }\r\n    ];\r\n\r\n    scrudFactory.card = {\r\n      " +
"  header: \"category_name\",\r\n        meta: \"alias\",\r\n        description: \"seo_de" +
"scription\"\r\n    };\r\n\r\n\r\n\r\n    $.get(\'/ScrudFactory/View.html\', function (view) {" +
"\r\n        $.get(\'/ScrudFactory/Form.html\', function (form) {\r\n            $(\"#Sc" +
"rudFactoryView\").html(view);\r\n            $(\"#ScrudFactoryForm\").html(form);\r\n  " +
"          $.cachedScript(\"/assets/js/scrudfactory-view.js\");\r\n            $.cach" +
"edScript(\"/assets/js/scrudfactory-form.js\");\r\n        });\r\n    });\r\n</script>\r\n\r" +
"\n\r\n\r\n\r\n<script>\r\n    $(document).on(\"formready\", function () {\r\n\r\n        $(\"#ca" +
"tegory_name\").keyup(function () {\r\n            function getAlias(title) {\r\n     " +
"           return title.toLowerCase().replace(/ +(?= )/g, \'\').replace(/ /g, \'-\')" +
".replace(/[^\\w-]+/g, \'\');\r\n            };\r\n\r\n            var category = $(this)." +
"val();\r\n            var alias = getAlias(category);\r\n\r\n            $(\"#alias\").v" +
"al(alias);\r\n\r\n        });\r\n    });\r\n</script>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
