#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Account;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/User/ChangePassword.cshtml")]
    public partial class _Views_User_ChangePassword_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_User_ChangePassword_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\User\ChangePassword.cshtml"
  
    ViewBag.Title = "User Management";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/validator.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n<div");

WriteLiteral(" class=\"ui segment\"");

WriteLiteral(" style=\"padding: 48px;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">Change Password</div>\r\n        <div");

WriteLiteral(" class=\"ui stackable grid\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"six wide column\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui big form\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                        <label>Select a User</label>\r\n                        " +
"<select");

WriteLiteral(" id=\"UserIdSelect\"");

WriteLiteral(" class=\"ui search dropdown\"");

WriteLiteral(" required=\"\"");

WriteLiteral("></select>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                        <label>Password</label>\r\n                        <inpu" +
"t");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"PasswordInputPassword\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                        <label>Confirm Password</label>\r\n                     " +
"   <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"ConfirmPasswordInputPassword\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <button");

WriteLiteral(" class=\"ui green big button\"");

WriteLiteral(" id=\"ChangeButton\"");

WriteLiteral(">Change</button>\r\n                </div>\r\n            </div>\r\n        </div>\r\n   " +
" </div>    \r\n</div>\r\n\r\n<script>\r\n    $(\".form\").addClass(\"loading\");\r\n    //$(\"." +
"dropdown\").dropdown();\r\n    window.validator.initialize($(\".ui.form\"));\r\n\r\n    f" +
"unction bindUsers() {\r\n        function request() {\r\n            var url = \"/api" +
"/views/account/user-selector-view/display-fields\";\r\n            return window.ge" +
"tAjaxRequest(url);\r\n        };\r\n\r\n        var ajax = request();\r\n\r\n        ajax." +
"fail(function () {\r\n            $(\".form\").removeClass(\"loading\");\r\n        });\r" +
"\n\r\n        ajax.success(function (response) {\r\n            $(\".form\").removeClas" +
"s(\"loading\");\r\n\r\n            var select = $(\"#UserIdSelect\");\r\n            var o" +
"ptions = \"\";\r\n\r\n            $.each(response, function () {\r\n                var " +
"option = \"<option value=\'{key}\'>{value}</option>\";\r\n                option = opt" +
"ion.replace(\"{key}\", this.Key);\r\n                option = option.replace(\"{value" +
"}\", this.Value);\r\n\r\n                options += option;\r\n            });\r\n\r\n     " +
"       select.html(options);\r\n        });\r\n    };\r\n\r\n    bindUsers();\r\n\r\n\r\n    $" +
"(\"#ChangeButton\").unbind(\"click\").bind(\"click\", function () {\r\n        function " +
"request(model) {\r\n            var url = \"/dashboard/account/user/change-password" +
"\";\r\n            var data = JSON.stringify(model);\r\n\r\n            return window.g" +
"etAjaxRequest(url, \"POST\", data);\r\n        };\r\n\r\n        var form = $(\".ui.form\"" +
");\r\n        form.addClass(\"loading\");\r\n\r\n        var model = window.serializeFor" +
"m(form);\r\n        if (model.Password !== model.ConfirmPassword) {\r\n            a" +
"lert(\"Confirm password does not match with supplied password.\");\r\n            re" +
"turn;\r\n        };\r\n\r\n        var ajax = request(model);\r\n\r\n        ajax.success(" +
"function () {\r\n            form.removeClass(\"loading\");\r\n            $(\".ui.form" +
" input\").val(\"\");\r\n            window.displaySuccess();\r\n        });\r\n\r\n        " +
"ajax.fail(function (xhr) {\r\n            form.removeClass(\"loading\");\r\n          " +
"  alert(JSON.stringify(xhr));\r\n        });\r\n    });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
