#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Account;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/User/Index.cshtml")]
    public partial class _Views_User_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_User_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\User\Index.cshtml"
  
    ViewBag.Title = "User Management";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"Use" +
"r Management\";\r\n\r\n    scrudFactory.viewAPI = \"/api/views/account/user-scrud-view" +
"\";\r\n    scrudFactory.viewTableName = \"account.user_scrud_view\";\r\n\r\n    scrudFact" +
"ory.formAPI = \"/api/forms/account/users\";\r\n    scrudFactory.formTableName = \"acc" +
"ount.users\";\r\n\r\n    scrudFactory.excludedColumns = [\"audit_user_id\", \"audit_ts\"," +
" \"password\"];\r\n    scrudFactory.hiddenColumns = [\"Password\"];\r\n\r\n    scrudFactor" +
"y.allowDelete = true;\r\n    scrudFactory.allowEdit = false;\r\n\r\n    scrudFactory.l" +
"ive = \"Email\";\r\n\r\n    scrudFactory.layout = [\r\n        {\r\n            tab: \"\",\r\n" +
"            fields: [\r\n                [\"UserId\", \"\"],\r\n                [\"Email\"" +
", \"Name\"],\r\n                [\"OfficeId\", \"RoleId\"],\r\n                [\"Phone\", \"" +
"Status\"]\r\n            ]\r\n        }\r\n    ];\r\n\r\n    scrudFactory.card = {\r\n       " +
" header: \"name\"\r\n    };\r\n\r\n    scrudFactory.keys = [\r\n        {\r\n            pro" +
"perty: \"OfficeId\",\r\n            url: \'/api/forms/core/offices/display-fields\',\r\n" +
"            data: null,\r\n            valueField: \"Key\",\r\n            textField: " +
"\"Value\"\r\n        },\r\n        {\r\n            property: \"RoleId\",\r\n            url" +
": \'/api/forms/account/roles/display-fields\',\r\n            data: null,\r\n         " +
"   valueField: \"Key\",\r\n            textField: \"Value\"\r\n        }\r\n    ];\r\n\r\n    " +
"$.get(\'/ScrudFactory/View.html?id=\' + Math.random(), function(view) {\r\n        $" +
"(\"#ScrudFactoryView\").html(view);\r\n        $.cachedScript(\"/assets/js/scrudfacto" +
"ry-view.js\");\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
