#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Frapid.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ErrorHandlers/404.cshtml")]
    public partial class _Views_ErrorHandlers_404_cshtml : System.Web.Mvc.WebViewPage<Frapid.WebsiteBuilder.ViewModels.SearchResult>
    {
        public _Views_ErrorHandlers_404_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\ErrorHandlers\404.cshtml"
  
    ViewBag.Description = "";
    ViewBag.Title = "Content Not Found";
    Layout = Model.LayoutPath + Model.Layout;
    ViewBag.LayoutPath = Model.LayoutPath;
    ViewBag.NoIndex = true;

            
            #line default
            #line hidden
WriteLiteral(@"
<style>
    .http.not.found.segment {
        min-height: 700px;
    }
     .search.results .item { padding: 1.2em 0; }

    .search.results .item .header { font-size: 1.27em; }

    .search.results .item .link { color: green; }

    .search.results .item .result .posted.on { color: #888; }

    .search.results .item .result { max-width: 650px; }
</style>
<div");

WriteLiteral(" class=\"ui attached http not found segment\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui very relaxed container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui section red header\"");

WriteLiteral(">Content Not Found</div>\r\n        <p");

WriteLiteral(" class=\"ui negative message\"");

WriteLiteral(">The page or resource you are looking for does not exist or has been deleted.</p>" +
"\r\n        <div");

WriteLiteral(" class=\"ui horizontal divider divider\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"search icon\"");

WriteLiteral("></i>            \r\n        </div>\r\n\r\n");

            
            #line 32 "..\..\Views\ErrorHandlers\404.cshtml"
        
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\ErrorHandlers\404.cshtml"
         if (Model.Contents.Any())
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"vertically padded result section\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui search results\"");

WriteLiteral(">\r\n");

            
            #line 36 "..\..\Views\ErrorHandlers\404.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\ErrorHandlers\404.cshtml"
                     foreach (var item in Model.Contents)
                {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1344), Tuple.Create("\"", 1364)
            
            #line 39 "..\..\Views\ErrorHandlers\404.cshtml"
, Tuple.Create(Tuple.Create("", 1351), Tuple.Create<System.Object, System.Int32>(item.LinkUrl
            
            #line default
            #line hidden
, 1351), false)
);

WriteLiteral(" class=\"header\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\ErrorHandlers\404.cshtml"
                                                              Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                            <div");

WriteLiteral(" class=\"link\"");

WriteLiteral(">");

            
            #line 40 "..\..\Views\ErrorHandlers\404.cshtml"
                                         Write(item.LinkUrl);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <div");

WriteLiteral(" class=\"result\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"posted on\"");

WriteLiteral(">");

            
            #line 42 "..\..\Views\ErrorHandlers\404.cshtml"
                                                   Write(item.LastUpdatedOn.ToString("u"));

            
            #line default
            #line hidden
WriteLiteral(" - </span>\r\n");

WriteLiteral("                                ");

            
            #line 43 "..\..\Views\ErrorHandlers\404.cshtml"
                           Write(item.Contents);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n");

            
            #line 46 "..\..\Views\ErrorHandlers\404.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n");

            
            #line 49 "..\..\Views\ErrorHandlers\404.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
