EXECUTE i18n.add_localized_resource 'Titles', '', 'SignIn', 'Sign In';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Username', 'Username';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Password', 'Password';
EXECUTE i18n.add_localized_resource 'Titles', '', 'ReturnToWebsite', 'Return to Website';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Or', 'Or';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Add', 'Add';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Save', 'Save';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Actions', 'Actions';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Edit', 'Edit';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Delete', 'Delete';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Update', 'Update';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Select', 'Select';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Approve', 'Approve';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Reject', 'Reject';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Close', 'Close';
EXECUTE i18n.add_localized_resource 'Titles', '', 'ReturnToView', 'Return to View';
EXECUTE i18n.add_localized_resource 'Titles', '', 'CreateDuplicate', 'Create Duplicate';
EXECUTE i18n.add_localized_resource 'Titles', '', 'None', 'None';
EXECUTE i18n.add_localized_resource 'Titles', '', 'First', 'First';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Previous', 'Previous';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Next', 'Next';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Last', 'Last';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Loading', 'Loading';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Update', 'Update';
EXECUTE i18n.add_localized_resource 'Titles', '', 'CreateNew', 'Create New';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Verification', 'Verification';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Reason', 'Reason';
EXECUTE i18n.add_localized_resource 'Titles', '', 'AddAKanbanList', 'Add a Kanban List';
EXECUTE i18n.add_localized_resource 'Titles', '', 'KanbanId', 'KanbanId';
EXECUTE i18n.add_localized_resource 'Titles', '', 'KanbanName', 'KanbanName';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Description', 'Description';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Cancel', 'Cancel';
EXECUTE i18n.add_localized_resource 'Titles', '', 'OK', 'OK';
EXECUTE i18n.add_localized_resource 'Titles', '', 'AddNew', 'Add New';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Filter', 'Filter';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Export', 'Export';
EXECUTE i18n.add_localized_resource 'Titles', '', 'ExportThisDocument', 'Export This Document';
EXECUTE i18n.add_localized_resource 'Titles', '', 'ExportToDoc', 'Export to Doc';
EXECUTE i18n.add_localized_resource 'Titles', '', 'ExportToExcel', 'Export to Excel';
EXECUTE i18n.add_localized_resource 'Titles', '', 'ExportToPDF', 'Export to PDF';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Print', 'Print';
EXECUTE i18n.add_localized_resource 'Titles', '', 'SelectAColumn', 'Select a Column';
EXECUTE i18n.add_localized_resource 'Titles', '', 'FilterCondition', 'Filter Condition';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Value', 'Value';
EXECUTE i18n.add_localized_resource 'Titles', '', 'And', 'And';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Add', 'Add';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Actions', 'Actions';
EXECUTE i18n.add_localized_resource 'Titles', '', 'ColumnName', 'Column Name';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Condition', 'Condition';
EXECUTE i18n.add_localized_resource 'Titles', '', 'SaveThisFilter', 'Save This Filter';
EXECUTE i18n.add_localized_resource 'Titles', '', 'FilterName', 'Filter Name';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Save', 'Save';
EXECUTE i18n.add_localized_resource 'Titles', '', 'ManageFilters', 'Manage Filters';
EXECUTE i18n.add_localized_resource 'Titles', '', 'RemoveAsDefault', 'Remove As Default';
EXECUTE i18n.add_localized_resource 'Titles', '', 'MakeAsDefault', 'Make As Default';
EXECUTE i18n.add_localized_resource 'Titles', '', 'DataImport', 'Data Import';
EXECUTE i18n.add_localized_resource 'Titles', '', 'ExportData', 'Export Data';
EXECUTE i18n.add_localized_resource 'Titles', '', 'ImportData', 'Import Data';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Yes', 'Yes';
EXECUTE i18n.add_localized_resource 'Titles', '', 'No', 'No';
EXECUTE i18n.add_localized_resource 'Titles', '', 'View', 'View';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Rating', 'Rating';
EXECUTE i18n.add_localized_resource 'Titles', '', 'AddNewChecklist', 'Add New Checklist';
EXECUTE i18n.add_localized_resource 'Titles', '', 'EditThisChecklist', 'Edit This Checklist';
EXECUTE i18n.add_localized_resource 'Titles', '', 'DeleteThisChecklist', 'Delete This Checklist';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Verify', 'Verify';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Back', 'Back';
EXECUTE i18n.add_localized_resource 'Titles', '', 'PageN', 'Page {0}';
EXECUTE i18n.add_localized_resource 'Titles', '', 'SelectAFilter', 'Select a Filter';
EXECUTE i18n.add_localized_resource 'Titles', '', 'CustomFields', 'Custom Fields';
EXECUTE i18n.add_localized_resource 'Titles', '', 'Untitled', 'Untitled';
EXECUTE i18n.add_localized_resource 'Labels', '', 'UploadInvalidTryAgain', 'Your upload is of invalid file type "{0}". Please try again.';
EXECUTE i18n.add_localized_resource 'Labels', '', 'ProcessingYourCSVFile', 'Processing  your CSV file.';
EXECUTE i18n.add_localized_resource 'Labels', '', 'SuccessfullyProcessedYourFile', 'Successfully processed your file.';
EXECUTE i18n.add_localized_resource 'Labels', '', 'RequestingImport', 'Requesting import. This may take several minutes to complete.';
EXECUTE i18n.add_localized_resource 'Labels', '', 'NoFormFound', 'No instance of form was found.';
EXECUTE i18n.add_localized_resource 'Labels', '', 'ImportedNItems', 'Successfully imported {0} items.';
EXECUTE i18n.add_localized_resource 'Labels', '', 'RollingBackChanges', 'Rolling back changes.';
EXECUTE i18n.add_localized_resource 'Warnings', '', 'InvalidFileExtension', 'Invalid file extension.';
EXECUTE i18n.add_localized_resource 'Questions', '', 'AreYouSure', 'Are you sure?';
EXECUTE i18n.add_localized_resource 'Questions', '', 'ColumnInvalidAreYouSure', 'The column "{0}" does not exist or is invalid. Are you sure you want to continue?';
EXECUTE i18n.add_localized_resource 'Questions', '', 'TaskCompletedSuccessfullyReturnToView', 'Task completed successfully. Return to view?';
EXECUTE i18n.add_localized_resource 'Labels', '', 'NHours', '{0} hour(s).';
EXECUTE i18n.add_localized_resource 'Labels', '', 'NMinutes', '{0} minute(s).';
EXECUTE i18n.add_localized_resource 'Labels', '', 'ItemDuplicated', 'Item duplicated.';
EXECUTE i18n.add_localized_resource 'Labels', '', 'TaskCompletedSuccessfully', 'Task completed successfully.';
EXECUTE i18n.add_localized_resource 'Labels', '', 'ThisFieldIsRequired', 'This field is required.';
EXECUTE i18n.add_localized_resource 'Labels', '', 'NamedFilter', 'Filter: {0}.';
EXECUTE i18n.add_localized_resource 'DbErrors', '', 'TableNotFound', 'The table was not found.';
