#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Dashboard;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Default/Index.cshtml")]
    public partial class _Views_Default_Index_cshtml : System.Web.Mvc.WebViewPage<Frapid.Dashboard.ViewModels.Dashboard>
    {
        public _Views_Default_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Default\Index.cshtml"
  
    ViewBag.Title = "Frapid Dashboard";
    Layout = ViewBag.LayoutPath + ViewBag.LayoutFile;

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
