#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Reports;
    
    #line 1 "..\..\Views\Index.cshtml"
    using Frapid.Reports.Engine.Model;
    
    #line default
    #line hidden
    using Frapid.WebsiteBuilder;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Index.cshtml")]
    public partial class _Views_Index_cshtml : System.Web.Mvc.WebViewPage<Frapid.Reports.ViewModels.ParameterMeta>
    {
        public _Views_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Index.cshtml"
  
    ViewBag.Title = "Frapid Dashboard";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral(@"


<style>
    #dashboard-container {
        padding: 1em 0 !important;
    }

    .padded.container {
        padding: 2em !important;
    }

    .collapsed.column {
        padding: 0 !important;
    }

    .pusher, .ng-scope {
        height: 100% !important;
    }

    .report-panel {
        background-color: #949596;
        padding-bottom: 4em;
    }

    .toolbar {
        background-color: #444;
        height: 3em;
        text-align: left;
        padding-left: 1em;
    }

        .toolbar .button {
            display: inline-flex;
            font-size: 0.8em;
            cursor: pointer;
            padding: 0.8em;
            height: 3.5em;
            width: 2.5em;
            margin: 2px;
            color: #dadada;
            text-shadow: 2px 2px 20px white;
        }

            .toolbar .button:hover {
                background-color: green;
            }

    iframe {
        width: 1000px;
        background-color: #fafafa;
        border: none;
        display: block;
        margin: 0 auto;
        height: 100%;
        overflow: auto;
        padding: 2em 2em 0 2em;
    }

    .vertically.very.relaxed {
        padding: 3em 0;
    }

    .header {
        font-weight: 100 !important;
    }

    .filter.container {
        padding: 1em;
    }
</style>
<div");

WriteLiteral(" class=\"report-panel\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui stackable report grid\"");

WriteLiteral(" style=\"height: 100%;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"three wide collapsed column\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" onclick=\"$(\'iframe\').get(0).contentWindow.print();\"");

WriteLiteral(" class=\"print button\"");

WriteLiteral(" title=\"Print This Report\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"print icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"mail button\"");

WriteLiteral(" title=\"Email This Report\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"mail icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"pdf button\"");

WriteLiteral(" title=\"Download PDF\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file pdf outline icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"excel button\"");

WriteLiteral(" title=\"Download Excel\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file excel outline icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"word button\"");

WriteLiteral(" title=\"Download Word\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file word outline icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"xml button\"");

WriteLiteral(" title=\"Download XML\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"code icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"text button\"");

WriteLiteral(" title=\"Download Text\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file text outline icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"zoom in button\"");

WriteLiteral(" title=\"Zoom In\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"zoom icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"zoom out button\"");

WriteLiteral(" title=\"Zoom Out\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"zoom icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" onclick=\"document.location = document.location\"");

WriteLiteral(" class=\"refresh button\"");

WriteLiteral(" title=\"Refresh\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"refresh icon\"");

WriteLiteral("></i>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"filter padded container\"");

WriteLiteral(" style=\"background-color: #efefef; height: 100%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">");

            
            #line 114 "..\..\Views\Index.cshtml"
                                       Write(Model.ReportTitle);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n                <div");

WriteLiteral(" class=\"ui small parameter form\"");

WriteLiteral(">\r\n");

            
            #line 117 "..\..\Views\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 117 "..\..\Views\Index.cshtml"
                     foreach (var parameter in Model.Parameters)
                    {
                        string name = parameter.Name.Replace("@", "");


            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>");

            
            #line 122 "..\..\Views\Index.cshtml"
                              Write(parameter.FieldLabel);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\r\n");

            
            #line 124 "..\..\Views\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 124 "..\..\Views\Index.cshtml"
                             if (!string.IsNullOrWhiteSpace(parameter.PopulateFrom))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <select");

WriteLiteral(" data-paramter=\"");

            
            #line 126 "..\..\Views\Index.cshtml"
                                                  Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 3930), Tuple.Create("\"", 3948)
            
            #line 126 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3935), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 3935), false)
, Tuple.Create(Tuple.Create("", 3942), Tuple.Create("Select", 3942), true)
);

WriteLiteral("\r\n                                        class=\"ui search dropdown\"");

WriteLiteral("\r\n                                        data-key-field=\"");

            
            #line 128 "..\..\Views\Index.cshtml"
                                                   Write(parameter.KeyField);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                        data-value-field=\"");

            
            #line 129 "..\..\Views\Index.cshtml"
                                                     Write(parameter.ValueField);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                        data-default-value=\"");

            
            #line 130 "..\..\Views\Index.cshtml"
                                                       Write(parameter.DefaultValue);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                        data-url=\"");

            
            #line 131 "..\..\Views\Index.cshtml"
                                             Write(parameter.PopulateFrom);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></select>\r\n");

            
            #line 132 "..\..\Views\Index.cshtml"
                            }
                            else
                            {
                                switch (parameter.Type)
                                {
                                    case DataSourceParameterType.Date:

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" data-paramter=\"");

            
            #line 138 "..\..\Views\Index.cshtml"
                                                         Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 4679), Tuple.Create("\"", 4700)
            
            #line 138 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4684), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 4684), false)
, Tuple.Create(Tuple.Create("", 4691), Tuple.Create("InputDate", 4691), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 4701), Tuple.Create("\"", 4732)
            
            #line 138 "..\..\Views\Index.cshtml"
                  , Tuple.Create(Tuple.Create("", 4709), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 4709), false)
);

WriteLiteral(" class=\"date\"");

WriteLiteral(" type=\"date\"");

WriteLiteral(" />\r\n");

            
            #line 139 "..\..\Views\Index.cshtml"
                                        break;
                                    case DataSourceParameterType.Bool:

            
            #line default
            #line hidden
WriteLiteral("                                        <div");

WriteLiteral(" class=\"ui toggle checkbox\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" data-paramter=\"");

            
            #line 142 "..\..\Views\Index.cshtml"
                                                             Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5029), Tuple.Create("\"", 5050)
            
            #line 142 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5034), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 5034), false)
, Tuple.Create(Tuple.Create("", 5041), Tuple.Create("InputDate", 5041), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 5051), Tuple.Create("\"", 5082)
            
            #line 142 "..\..\Views\Index.cshtml"
                      , Tuple.Create(Tuple.Create("", 5059), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 5059), false)
);

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(">\r\n                                            <label>Yes</label>\r\n              " +
"                          </div>\r\n");

            
            #line 145 "..\..\Views\Index.cshtml"
                                        break;
                                    case DataSourceParameterType.Decimal:
                                    case DataSourceParameterType.Double:
                                    case DataSourceParameterType.Number:

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" data-paramter=\"");

            
            #line 149 "..\..\Views\Index.cshtml"
                                                         Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5553), Tuple.Create("\"", 5574)
            
            #line 149 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5558), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 5558), false)
, Tuple.Create(Tuple.Create("", 5565), Tuple.Create("InputText", 5565), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 5575), Tuple.Create("\"", 5606)
            
            #line 149 "..\..\Views\Index.cshtml"
                  , Tuple.Create(Tuple.Create("", 5583), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 5583), false)
);

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"decimal\"");

WriteLiteral(" data-number=\"\"");

WriteLiteral(" />\r\n");

            
            #line 150 "..\..\Views\Index.cshtml"
                                        break;
                                    default:

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" data-paramter=\"");

            
            #line 152 "..\..\Views\Index.cshtml"
                                                         Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5817), Tuple.Create("\"", 5838)
            
            #line 152 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5822), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 5822), false)
, Tuple.Create(Tuple.Create("", 5829), Tuple.Create("InputText", 5829), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 5839), Tuple.Create("\"", 5870)
            
            #line 152 "..\..\Views\Index.cshtml"
                  , Tuple.Create(Tuple.Create("", 5847), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 5847), false)
);

WriteLiteral(" type=\"text\"");

WriteLiteral(" />\r\n");

            
            #line 153 "..\..\Views\Index.cshtml"
                                        break;
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n");

            
            #line 157 "..\..\Views\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" id=\"ShowButton\"");

WriteLiteral(" class=\"ui positive button\"");

WriteLiteral(">Show</button>\r\n                </div>\r\n            </div>\r\n        </div>\r\n     " +
"   <div");

WriteLiteral(" class=\"thirteen wide column\"");

WriteLiteral(">\r\n            <iframe");

WriteAttribute("src", Tuple.Create(" src=\"", 6266), Tuple.Create("\"", 6295)
            
            #line 163 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 6272), Tuple.Create<System.Object, System.Int32>(Model.ReportSourcePath
            
            #line default
            #line hidden
, 6272), false)
);

WriteLiteral("></iframe>\r\n        </div>\r\n    </div>\r\n</div>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n<script>\r\n    $(\".dropdown\").dropdown();\r\n    loadDatepicker();\r\n    " +
"(function () {\r\n\r\n        var persist = JSON.parse(localStorage.getItem(document" +
".location.pathname));\r\n\r\n        if (persist) {\r\n            $.each(persist, fun" +
"ction () {\r\n                var el = $(\"#\" + this.id);\r\n                var valu" +
"e = this.value;\r\n                var defaultValue;\r\n\r\n                if (el.is(" +
"\"select\")) {\r\n                    defaultValue = el.attr(\"data-default-value\");\r" +
"\n                    if (!defaultValue) {\r\n                        el.attr(\"data" +
"-default-value\", value);\r\n                    };\r\n                } else {\r\n    " +
"                defaultValue = el.val();\r\n                    if (!defaultValue)" +
" {\r\n\r\n                        if (el.is(\".date\")) {\r\n                           " +
" var date = new Date(value);\r\n\r\n                            el.datepicker(\"setDa" +
"te\", date);\r\n                        } else {\r\n                            el.va" +
"l(value);\r\n                        };\r\n                    };\r\n                }" +
";\r\n\r\n            });\r\n        };\r\n\r\n        var candidates = $(\"select[data-url]" +
"\");\r\n\r\n        $.each(candidates, function () {\r\n            var el = $(this);\r\n" +
"            var url = el.attr(\"data-url\");\r\n            var keyField = el.attr(\"" +
"data-key-field\");\r\n            var valueField = el.attr(\"data-value-field\");\r\n  " +
"          var defaultValue = el.attr(\"data-default-value\");\r\n\r\n\r\n            win" +
"dow.ajaxDataBind(url, el, null, defaultValue, null, function () {\r\n             " +
"   setTimeout(function () {\r\n                    el.dropdown(\"set selected\", def" +
"aultValue);\r\n                },\r\n                    100);\r\n            }, keyFi" +
"eld, valueField, false);\r\n        });\r\n    })();\r\n\r\n    $(\"#ShowButton\")\r\n      " +
"  .unbind(\"click\")\r\n        .bind(\"click\",\r\n            function () {\r\n         " +
"       var persist = [];\r\n\r\n                var query = [];\r\n\r\n                v" +
"ar dateEls = $(\".parameter.form .field input.date\");\r\n\r\n                $.each(d" +
"ateEls,\r\n                    function () {\r\n                        var el = $(t" +
"his);\r\n                        var parameter = el.attr(\"data-paramter\");\r\n      " +
"                  var value = el.datepicker(\"getDate\").valueOf();\r\n             " +
"           var id = el.attr(\"id\");\r\n\r\n                        persist.push({\r\n  " +
"                          id: id,\r\n                            value: value\r\n   " +
"                     });\r\n\r\n                        if (parameter) {\r\n          " +
"                  query.push(parameter + \"=\" + value);\r\n                        " +
"};\r\n                    });\r\n\r\n                var otherEls = $(\".parameter.form" +
" .field input:not(.date), .parameter.form .field select\");\r\n\r\n                $." +
"each(otherEls,\r\n                    function () {\r\n                        var e" +
"l = $(this);\r\n                        var parameter = el.attr(\"data-paramter\");\r" +
"\n                        var value = el.val();\r\n\r\n                        var id" +
" = el.attr(\"id\");\r\n\r\n                        persist.push({\r\n                   " +
"         id: id,\r\n                            value: value\r\n                    " +
"    });\r\n\r\n                        if (parameter) {\r\n                           " +
" query.push(parameter + \"=\" + value);\r\n                        };\r\n             " +
"       });\r\n\r\n                localStorage.setItem(document.location.pathname, J" +
"SON.stringify(persist));\r\n\r\n                var location = document.location.pat" +
"hname + \"?\" + query.join(\"&\");\r\n                document.location = location;\r\n " +
"           });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
