#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Reports;
    using Frapid.WebsiteBuilder;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Index.cshtml")]
    public partial class _Views_Index_cshtml : System.Web.Mvc.WebViewPage<Frapid.Reports.ViewModels.ParameterMeta>
    {
        public _Views_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Index.cshtml"
  
    ViewBag.Title = "Frapid Dashboard";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral(@"


<style>
    #dashboard-container { padding: 1em 0 !important; }

    .padded.container { padding: 2em !important; }

    .collapsed.column { padding: 0 !important; }

    .pusher, .ng-scope { height: 100% !important; }

    .report-panel {
        background-color: #949596;
        padding-bottom: 4em;
    }

    .toolbar {
        background-color: #444;
        height: 3em;
        padding-left: 1em;
        text-align: left;
    }

    .toolbar .button {
        color: #dadada;
        cursor: pointer;
        display: inline-flex;
        font-size: 0.8em;
        height: 3.5em;
        margin: 2px;
        padding: 0.8em;
        text-shadow: 2px 2px 20px white;
        width: 2.5em;
    }

    .toolbar .button:hover { background-color: green; }

    iframe {
        background-color: #fafafa;
        border: none;
        display: block;
        height: 100%;
        margin: 0 auto;
        overflow: auto;
        padding: 2em 2em 0 2em;
        width: 1000px;
    }

    .vertically.very.relaxed { padding: 3em 0; }

    .header { font-weight: 100 !important; }

    .filter.container { padding: 1em; }
</style>
<div");

WriteLiteral(" class=\"report-panel\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui stackable report grid\"");

WriteLiteral(" style=\"height: 100%;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"three wide collapsed column\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" onclick=\"$(\'iframe\').get(0).contentWindow.print();\"");

WriteLiteral(" class=\"print button\"");

WriteLiteral(" title=\"Print This Report\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"print icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"mail button\"");

WriteLiteral(" title=\"Email This Report\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"mail icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"pdf button\"");

WriteLiteral(" title=\"Download PDF\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file pdf outline icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"excel button\"");

WriteLiteral(" title=\"Download Excel\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file excel outline icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"word button\"");

WriteLiteral(" title=\"Download Word\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file word outline icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"xml button\"");

WriteLiteral(" title=\"Download XML\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"code icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"text button\"");

WriteLiteral(" title=\"Download Text\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file text outline icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"zoom in button\"");

WriteLiteral(" title=\"Zoom In\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"zoom icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"zoom out button\"");

WriteLiteral(" title=\"Zoom Out\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"zoom icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" onclick=\"document.location = document.location\"");

WriteLiteral(" class=\"refresh button\"");

WriteLiteral(" title=\"Refresh\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"refresh icon\"");

WriteLiteral("></i>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"filter padded container\"");

WriteLiteral(" style=\"background-color: #efefef; height: 100%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">");

            
            #line 97 "..\..\Views\Index.cshtml"
                                       Write(Model.ReportTitle);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n                <div");

WriteLiteral(" class=\"ui small parameter form\"");

WriteLiteral(">\r\n");

            
            #line 100 "..\..\Views\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 100 "..\..\Views\Index.cshtml"
                     foreach (var parameter in Model.Parameters)
                    {
                        string name = parameter.Name.Replace("@", "");


            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>");

            
            #line 105 "..\..\Views\Index.cshtml"
                              Write(parameter.FieldLabel);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\r\n");

            
            #line 107 "..\..\Views\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 107 "..\..\Views\Index.cshtml"
                             if (!string.IsNullOrWhiteSpace(parameter.PopulateFrom))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <select");

WriteLiteral(" data-paramter=\"");

            
            #line 109 "..\..\Views\Index.cshtml"
                                                  Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 3714), Tuple.Create("\"", 3732)
            
            #line 109 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3719), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 3719), false)
, Tuple.Create(Tuple.Create("", 3726), Tuple.Create("Select", 3726), true)
);

WriteLiteral("\r\n                                        class=\"ui search dropdown\"");

WriteLiteral("\r\n                                        data-key-field=\"");

            
            #line 111 "..\..\Views\Index.cshtml"
                                                   Write(parameter.KeyField);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                        data-value-field=\"");

            
            #line 112 "..\..\Views\Index.cshtml"
                                                     Write(parameter.ValueField);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                        data-default-value=\"");

            
            #line 113 "..\..\Views\Index.cshtml"
                                                       Write(parameter.DefaultValue);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                        data-url=\"");

            
            #line 114 "..\..\Views\Index.cshtml"
                                             Write(parameter.PopulateFrom);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                </select>\r\n");

            
            #line 116 "..\..\Views\Index.cshtml"
                            }
                            else
                            {
                                switch (parameter.Type.ToUpperInvariant())
                                {
                                    case "SYSTEM.DATETIME":

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" data-paramter=\"");

            
            #line 122 "..\..\Views\Index.cshtml"
                                                         Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 4505), Tuple.Create("\"", 4526)
            
            #line 122 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4510), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 4510), false)
, Tuple.Create(Tuple.Create("", 4517), Tuple.Create("InputDate", 4517), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 4527), Tuple.Create("\"", 4558)
            
            #line 122 "..\..\Views\Index.cshtml"
                  , Tuple.Create(Tuple.Create("", 4535), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 4535), false)
);

WriteLiteral(" class=\"date\"");

WriteLiteral(" type=\"date\"");

WriteLiteral("/>\r\n");

            
            #line 123 "..\..\Views\Index.cshtml"
                                        break;
                                    case "BOOL":
                                    case "BOOLEAN":

            
            #line default
            #line hidden
WriteLiteral("                                        <div");

WriteLiteral(" class=\"ui toggle checkbox\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" data-paramter=\"");

            
            #line 127 "..\..\Views\Index.cshtml"
                                                             Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 4885), Tuple.Create("\"", 4906)
            
            #line 127 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4890), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 4890), false)
, Tuple.Create(Tuple.Create("", 4897), Tuple.Create("InputDate", 4897), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 4907), Tuple.Create("\"", 4938)
            
            #line 127 "..\..\Views\Index.cshtml"
                      , Tuple.Create(Tuple.Create("", 4915), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 4915), false)
);

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(">\r\n                                            <label>Yes</label>\r\n              " +
"                          </div>\r\n");

            
            #line 130 "..\..\Views\Index.cshtml"
                                        break;
                                    case "DECIMAL":
                                    case "DOUBLE":

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" data-paramter=\"");

            
            #line 133 "..\..\Views\Index.cshtml"
                                                         Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5291), Tuple.Create("\"", 5312)
            
            #line 133 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5296), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 5296), false)
, Tuple.Create(Tuple.Create("", 5303), Tuple.Create("InputText", 5303), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 5313), Tuple.Create("\"", 5344)
            
            #line 133 "..\..\Views\Index.cshtml"
                  , Tuple.Create(Tuple.Create("", 5321), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 5321), false)
);

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"decimal\"");

WriteLiteral(" data-number=\"\"");

WriteLiteral("/>\r\n");

            
            #line 134 "..\..\Views\Index.cshtml"
                                        break;
                                    case "INT":
                                    case "LONG":

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" data-paramter=\"");

            
            #line 137 "..\..\Views\Index.cshtml"
                                                         Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5607), Tuple.Create("\"", 5628)
            
            #line 137 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5612), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 5612), false)
, Tuple.Create(Tuple.Create("", 5619), Tuple.Create("InputText", 5619), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 5629), Tuple.Create("\"", 5660)
            
            #line 137 "..\..\Views\Index.cshtml"
                  , Tuple.Create(Tuple.Create("", 5637), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 5637), false)
);

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" data-number=\"\"");

WriteLiteral("/>\r\n");

            
            #line 138 "..\..\Views\Index.cshtml"
                                        break;
                                    default:

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" data-paramter=\"");

            
            #line 140 "..\..\Views\Index.cshtml"
                                                         Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5870), Tuple.Create("\"", 5891)
            
            #line 140 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5875), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 5875), false)
, Tuple.Create(Tuple.Create("", 5882), Tuple.Create("InputText", 5882), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 5892), Tuple.Create("\"", 5923)
            
            #line 140 "..\..\Views\Index.cshtml"
                  , Tuple.Create(Tuple.Create("", 5900), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 5900), false)
);

WriteLiteral(" type=\"text\"");

WriteLiteral("/>\r\n");

            
            #line 141 "..\..\Views\Index.cshtml"
                                        break;
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n");

            
            #line 145 "..\..\Views\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" id=\"ShowButton\"");

WriteLiteral(" class=\"ui positive button\"");

WriteLiteral(">Show</button>\r\n                </div>\r\n            </div>\r\n        </div>\r\n     " +
"   <div");

WriteLiteral(" class=\"thirteen wide column\"");

WriteLiteral(">\r\n            <iframe");

WriteAttribute("src", Tuple.Create(" src=\"", 6318), Tuple.Create("\"", 6347)
            
            #line 151 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 6324), Tuple.Create<System.Object, System.Int32>(Model.ReportSourcePath
            
            #line default
            #line hidden
, 6324), false)
);

WriteLiteral("></iframe>\r\n        </div>\r\n    </div>\r\n</div>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n<script>\r\n    $(\".dropdown\").dropdown();\r\n    loadDatepicker();\r\n    " +
"(function() {\r\n\r\n        const persist = JSON.parse(localStorage.getItem(documen" +
"t.location.pathname));\r\n\r\n        if (persist) {\r\n            $.each(persist, fu" +
"nction() {\r\n                const el = $(`#${this.id}`);\r\n                const " +
"value = this.value;\r\n                var defaultValue;\r\n\r\n                if (el" +
".is(\"select\")) {\r\n                    defaultValue = el.attr(\"data-default-value" +
"\");\r\n                    if (!defaultValue) {\r\n                        el.attr(\"" +
"data-default-value\", value);\r\n                    };\r\n                } else {\r\n" +
"                    defaultValue = el.val();\r\n                    if (!defaultVa" +
"lue) {\r\n\r\n                        if (el.is(\".date\")) {\r\n                       " +
"     const date = new Date(value);\r\n\r\n                            el.datepicker(" +
"\"setDate\", date);\r\n                        } else {\r\n                           " +
" el.val(value);\r\n                        };\r\n                    };\r\n           " +
"     };\r\n\r\n            });\r\n        };\r\n\r\n        const candidates = $(\"select[d" +
"ata-url]\");\r\n\r\n        $.each(candidates, function() {\r\n            var el = $(t" +
"his);\r\n            const url = el.attr(\"data-url\");\r\n            const keyField " +
"= el.attr(\"data-key-field\");\r\n            const valueField = el.attr(\"data-value" +
"-field\");\r\n            var defaultValue = el.attr(\"data-default-value\");\r\n\r\n\r\n  " +
"          window.ajaxDataBind(url, el, null, defaultValue, null, function() {\r\n " +
"               setTimeout(function() {\r\n                        el.dropdown(\"set" +
" selected\", defaultValue);\r\n                    },\r\n                    100);\r\n " +
"           }, keyField, valueField, false);\r\n        });\r\n    })();\r\n\r\n    $(\"#S" +
"howButton\")\r\n        .unbind(\"click\")\r\n        .bind(\"click\",\r\n            funct" +
"ion() {\r\n                var persist = [];\r\n\r\n                var query = [];\r\n\r" +
"\n                const dateEls = $(\".parameter.form .field input.date\");\r\n\r\n    " +
"            $.each(dateEls,\r\n                    function() {\r\n                 " +
"       const el = $(this);\r\n                        const parameter = el.attr(\"d" +
"ata-paramter\");\r\n                        const value = el.datepicker(\"getDate\")." +
"valueOf();\r\n                        const id = el.attr(\"id\");\r\n\r\n               " +
"         persist.push({\r\n                            id: id,\r\n                  " +
"          value: value\r\n                        });\r\n\r\n                        i" +
"f (parameter) {\r\n                            query.push(parameter + \"=\" + value)" +
";\r\n                        };\r\n                    });\r\n\r\n                const " +
"otherEls = $(\".parameter.form .field input:not(.date), .parameter.form .field se" +
"lect\");\r\n\r\n                $.each(otherEls,\r\n                    function() {\r\n " +
"                       const el = $(this);\r\n                        const parame" +
"ter = el.attr(\"data-paramter\");\r\n                        const value = el.val();" +
"\r\n\r\n                        const id = el.attr(\"id\");\r\n\r\n                       " +
" persist.push({\r\n                            id: id,\r\n                          " +
"  value: value\r\n                        });\r\n\r\n                        if (param" +
"eter) {\r\n                            query.push(parameter + \"=\" + value);\r\n     " +
"                   };\r\n                    });\r\n\r\n                localStorage.s" +
"etItem(document.location.pathname, JSON.stringify(persist));\r\n\r\n                " +
"const location = document.location.pathname + \"?\" + query.join(\"&\");\r\n          " +
"      document.location = location;\r\n            });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
