#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Reports;
    using Frapid.WebsiteBuilder;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Index.cshtml")]
    public partial class _Views_Index_cshtml : System.Web.Mvc.WebViewPage<Frapid.Reports.ViewModels.ParameterMeta>
    {
        public _Views_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Index.cshtml"
  
    ViewBag.Title = "Frapid Dashboard";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral(@"


<style>
    #dashboard-container {
        padding: 1em 0 !important;
    }

    .padded.container {
        padding: 2em !important;
    }

    .collapsed.column {
        padding: 0 !important;
    }

    .pusher, .ng-scope {
        height: 100% !important;
    }

    .report-panel {
        background-color: #949596;
        padding-bottom: 4em;
    }

    .toolbar {
        background-color: #444;
        height: 3em;
        padding-left: 1em;
        text-align: left;
    }

        .toolbar .button {
            color: #dadada;
            cursor: pointer;
            display: inline-flex;
            font-size: 0.8em;
            height: 3.5em;
            margin: 2px;
            padding: 0.8em;
            text-shadow: 2px 2px 20px white;
            width: 2.5em;
        }

            .toolbar .button:hover {
                background-color: green;
            }

    iframe {
        background-color: #fafafa;
        border: none;
        display: block;
        height: 100%;
        margin: 0 auto;
        overflow: auto;
        padding: 2em 2em 0 2em;
        width: 1000px;
    }

    .vertically.very.relaxed {
        padding: 3em 0;
    }

    .filter.container {
        padding: 1em;
    }

    .report.title {
        font-size: 1.2em !important;
        padding: 0 0 1em 0;
        font-weight: 600;
        text-transform: uppercase;
        color: #666;
    }
</style>
<div");

WriteLiteral(" class=\"report-panel\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui stackable report grid\"");

WriteLiteral(" style=\"height: 100%;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"three wide collapsed column\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" onclick=\"$(\'iframe\').get(0).contentWindow.print();\"");

WriteLiteral(" class=\"print button\"");

WriteLiteral(" title=\"Print This Report\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"print icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"mail button\"");

WriteLiteral(" title=\"Email This Report\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"mail icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"pdf button\"");

WriteLiteral(" title=\"Download PDF\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file pdf outline icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"excel button\"");

WriteLiteral(" title=\"Download Excel\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file excel outline icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"word button\"");

WriteLiteral(" title=\"Download Word\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file word outline icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"xml button\"");

WriteLiteral(" title=\"Download XML\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"code icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"text button\"");

WriteLiteral(" title=\"Download Text\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file text outline icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"zoom in button\"");

WriteLiteral(" title=\"Zoom In\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"zoom icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"zoom out button\"");

WriteLiteral(" title=\"Zoom Out\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"zoom icon\"");

WriteLiteral("></i>\r\n                </div>\r\n                <div");

WriteLiteral(" onclick=\"document.location = document.location\"");

WriteLiteral(" class=\"refresh button\"");

WriteLiteral(" title=\"Refresh\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"refresh icon\"");

WriteLiteral("></i>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"filter padded container\"");

WriteLiteral(" style=\"background-color: #efefef; height: 100%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"report title\"");

WriteLiteral(">");

            
            #line 117 "..\..\Views\Index.cshtml"
                                     Write(Model.ReportTitle);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n                <div");

WriteLiteral(" class=\"ui small parameter form\"");

WriteLiteral(">\r\n");

            
            #line 120 "..\..\Views\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 120 "..\..\Views\Index.cshtml"
                     foreach (var parameter in Model.Parameters)
                    {
                        string name = parameter.Name.Replace("@", "");


            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>");

            
            #line 125 "..\..\Views\Index.cshtml"
                              Write(parameter.FieldLabel);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\r\n");

            
            #line 127 "..\..\Views\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 127 "..\..\Views\Index.cshtml"
                             if (!string.IsNullOrWhiteSpace(parameter.PopulateFrom))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <select");

WriteLiteral(" data-paramter=\"");

            
            #line 129 "..\..\Views\Index.cshtml"
                                                  Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 4012), Tuple.Create("\"", 4030)
            
            #line 129 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4017), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 4017), false)
, Tuple.Create(Tuple.Create("", 4024), Tuple.Create("Select", 4024), true)
);

WriteLiteral("\r\n                                        class=\"ui search dropdown\"");

WriteLiteral("\r\n                                        data-key-field=\"");

            
            #line 131 "..\..\Views\Index.cshtml"
                                                   Write(parameter.KeyField);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                        data-value-field=\"");

            
            #line 132 "..\..\Views\Index.cshtml"
                                                     Write(parameter.ValueField);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                        data-default-value=\"");

            
            #line 133 "..\..\Views\Index.cshtml"
                                                       Write(parameter.DefaultValue);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                        data-url=\"");

            
            #line 134 "..\..\Views\Index.cshtml"
                                             Write(parameter.PopulateFrom);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-optional=\"");

            
            #line 134 "..\..\Views\Index.cshtml"
                                                                                     Write(parameter.Optional.ToString().ToLowerInvariant());

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></select>\r\n");

            
            #line 135 "..\..\Views\Index.cshtml"
                            }
                            else
                            {
                                switch (parameter.Type.ToUpperInvariant())
                                {
                                    case "SYSTEM.DATETIME":

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" data-paramter=\"");

            
            #line 141 "..\..\Views\Index.cshtml"
                                                         Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 4835), Tuple.Create("\"", 4856)
            
            #line 141 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4840), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 4840), false)
, Tuple.Create(Tuple.Create("", 4847), Tuple.Create("InputDate", 4847), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 4857), Tuple.Create("\"", 4888)
            
            #line 141 "..\..\Views\Index.cshtml"
                  , Tuple.Create(Tuple.Create("", 4865), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 4865), false)
);

WriteLiteral(" class=\"date\"");

WriteLiteral(" type=\"date\"");

WriteLiteral(" />\r\n");

            
            #line 142 "..\..\Views\Index.cshtml"
                                        break;
                                    case "BOOL":
                                    case "BOOLEAN":

            
            #line default
            #line hidden
WriteLiteral("                                        <div");

WriteLiteral(" class=\"ui toggle checkbox\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" data-paramter=\"");

            
            #line 146 "..\..\Views\Index.cshtml"
                                                             Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5216), Tuple.Create("\"", 5237)
            
            #line 146 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5221), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 5221), false)
, Tuple.Create(Tuple.Create("", 5228), Tuple.Create("InputDate", 5228), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 5238), Tuple.Create("\"", 5269)
            
            #line 146 "..\..\Views\Index.cshtml"
                      , Tuple.Create(Tuple.Create("", 5246), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 5246), false)
);

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(">\r\n                                            <label>Yes</label>\r\n              " +
"                          </div>\r\n");

            
            #line 149 "..\..\Views\Index.cshtml"
                                        break;
                                    case "DECIMAL":
                                    case "DOUBLE":

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" data-paramter=\"");

            
            #line 152 "..\..\Views\Index.cshtml"
                                                         Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5622), Tuple.Create("\"", 5643)
            
            #line 152 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5627), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 5627), false)
, Tuple.Create(Tuple.Create("", 5634), Tuple.Create("InputText", 5634), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 5644), Tuple.Create("\"", 5675)
            
            #line 152 "..\..\Views\Index.cshtml"
                  , Tuple.Create(Tuple.Create("", 5652), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 5652), false)
);

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"decimal\"");

WriteLiteral(" data-number=\"\"");

WriteLiteral(" />\r\n");

            
            #line 153 "..\..\Views\Index.cshtml"
                                        break;
                                    case "INT":
                                    case "LONG":

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" data-paramter=\"");

            
            #line 156 "..\..\Views\Index.cshtml"
                                                         Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5939), Tuple.Create("\"", 5960)
            
            #line 156 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5944), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 5944), false)
, Tuple.Create(Tuple.Create("", 5951), Tuple.Create("InputText", 5951), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 5961), Tuple.Create("\"", 5992)
            
            #line 156 "..\..\Views\Index.cshtml"
                  , Tuple.Create(Tuple.Create("", 5969), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 5969), false)
);

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" data-number=\"\"");

WriteLiteral(" />\r\n");

            
            #line 157 "..\..\Views\Index.cshtml"
                                        break;
                                    default:

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" data-paramter=\"");

            
            #line 159 "..\..\Views\Index.cshtml"
                                                         Write(name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 6203), Tuple.Create("\"", 6224)
            
            #line 159 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 6208), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 6208), false)
, Tuple.Create(Tuple.Create("", 6215), Tuple.Create("InputText", 6215), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 6225), Tuple.Create("\"", 6256)
            
            #line 159 "..\..\Views\Index.cshtml"
                  , Tuple.Create(Tuple.Create("", 6233), Tuple.Create<System.Object, System.Int32>(parameter.DefaultValue
            
            #line default
            #line hidden
, 6233), false)
);

WriteLiteral(" type=\"text\"");

WriteLiteral(" />\r\n");

            
            #line 160 "..\..\Views\Index.cshtml"
                                        break;
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n");

            
            #line 164 "..\..\Views\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" id=\"ShowButton\"");

WriteLiteral(" class=\"ui positive button\"");

WriteLiteral(">Show</button>\r\n                </div>\r\n            </div>\r\n        </div>\r\n     " +
"   <div");

WriteLiteral(" class=\"thirteen wide column\"");

WriteLiteral(">\r\n            <iframe");

WriteAttribute("src", Tuple.Create(" src=\"", 6652), Tuple.Create("\"", 6681)
            
            #line 170 "..\..\Views\Index.cshtml"
, Tuple.Create(Tuple.Create("", 6658), Tuple.Create<System.Object, System.Int32>(Model.ReportSourcePath
            
            #line default
            #line hidden
, 6658), false)
);

WriteLiteral("></iframe>\r\n        </div>\r\n    </div>\r\n</div>\r\n<script>\r\n    $(\".dropdown\").drop" +
"down();\r\n    loadDatepicker();\r\n\r\n    (function () {\r\n        const persist = JS" +
"ON.parse(localStorage.getItem(document.location.pathname));\r\n\r\n        if (persi" +
"st) {\r\n            $.each(persist, function () {\r\n                const el = $(`" +
"#${this.id}`);\r\n                const value = this.value;\r\n                var d" +
"efaultValue;\r\n\r\n                if (el.is(\"select\")) {\r\n                    defa" +
"ultValue = el.attr(\"data-default-value\");\r\n\r\n                    if (!defaultVal" +
"ue) {\r\n                        el.attr(\"data-default-value\", value);\r\n          " +
"          };\r\n                } else {\r\n                    defaultValue = el.va" +
"l();\r\n                    if (!defaultValue) {\r\n\r\n                        if (el" +
".is(\".date\")) {\r\n                            const date = new Date(value);\r\n\r\n  " +
"                          el.datepicker(\"setDate\", date);\r\n                     " +
"   } else {\r\n                            el.val(value);\r\n                       " +
" };\r\n                    };\r\n                };\r\n\r\n            });\r\n        };\r\n" +
"\r\n        const candidates = $(\"select[data-url]\");\r\n\r\n        $.each(candidates" +
", function () {\r\n            var el = $(this);\r\n            const url = el.attr(" +
"\"data-url\");\r\n            const keyField = el.attr(\"data-key-field\");\r\n         " +
"   const valueField = el.attr(\"data-value-field\");\r\n            var defaultValue" +
" = el.attr(\"data-default-value\");\r\n            const optional = el.attr(\"data-op" +
"tional\").toLowerCase().indexOf(\"t\") > -1;\r\n\r\n\r\n            window.ajaxDataBind(u" +
"rl, el, null, defaultValue, null, function () {\r\n                setTimeout(func" +
"tion () {\r\n\r\n                    if (defaultValue) {\r\n                        el" +
".dropdown(\"set selected\", defaultValue);\r\n                    };\r\n\r\n            " +
"        if (optional) {\r\n                        el.prepend(\"<option value=\'null" +
"\'>Select</option>\");\r\n\r\n                        if (defaultValue === \"0\") {\r\n   " +
"                         el.dropdown(\"set text\", \"Select\");\r\n                   " +
"     };\r\n                    };\r\n                }, 100);\r\n\r\n            }, keyF" +
"ield, valueField, false);\r\n        });\r\n    })();\r\n\r\n    $(\"#ShowButton\").unbind" +
"(\"click\").bind(\"click\", function () {\r\n        var persist = [];\r\n\r\n        var " +
"query = [];\r\n\r\n        const dateEls = $(\".parameter.form .field input.date\");\r\n" +
"\r\n        $.each(dateEls, function () {\r\n            const el = $(this);\r\n      " +
"      const parameter = el.attr(\"data-paramter\");\r\n            const value = el." +
"datepicker(\"getDate\").valueOf();\r\n            const id = el.attr(\"id\");\r\n\r\n     " +
"       persist.push({\r\n                id: id,\r\n                value: value\r\n  " +
"          });\r\n\r\n            if (parameter) {\r\n                query.push(parame" +
"ter + \"=\" + value);\r\n            };\r\n        });\r\n\r\n        const otherEls = $(\"" +
".parameter.form .field input:not(.date), .parameter.form .field select\");\r\n\r\n   " +
"     $.each(otherEls, function () {\r\n            const el = $(this);\r\n          " +
"  const parameter = el.attr(\"data-paramter\");\r\n            const value = el.val(" +
");\r\n\r\n            const id = el.attr(\"id\");\r\n\r\n            persist.push({\r\n     " +
"           id: id,\r\n                value: value\r\n            });\r\n\r\n           " +
" if (parameter) {\r\n                query.push(parameter + \"=\" + value);\r\n       " +
"     };\r\n        });\r\n\r\n        localStorage.setItem(document.location.pathname," +
" JSON.stringify(persist));\r\n\r\n        const location = document.location.pathnam" +
"e + \"?\" + query.join(\"&\");\r\n        document.location = location;\r\n    });\r\n</sc" +
"ript>");

        }
    }
}
#pragma warning restore 1591
