#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Authorization;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MenuPolicy/Policy.cshtml")]
    public partial class _Views_MenuPolicy_Policy_cshtml : System.Web.Mvc.WebViewPage<Frapid.Authorization.ViewModels.UserMenuPolicy>
    {
        public _Views_MenuPolicy_Policy_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\MenuPolicy\Policy.cshtml"
  
    ViewBag.Title = "Menu Policy";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n    .selector.table tr { cursor: pointer; }\r\n</style>\r\n<div");

WriteLiteral(" class=\"ui container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui attached padded segment\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">Menu Access Policy</div>\r\n        <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"ui vpad8 form\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"three fields\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label>Select a User</label>\r\n                    <select");

WriteLiteral(" id=\"UserSelect\"");

WriteLiteral(" class=\"ui search dropdown\"");

WriteLiteral(">\r\n                        <option>Select</option>\r\n");

            
            #line 20 "..\..\Views\MenuPolicy\Policy.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\MenuPolicy\Policy.cshtml"
                         foreach (var item in Model.Users)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 778), Tuple.Create("\"", 798)
            
            #line 22 "..\..\Views\MenuPolicy\Policy.cshtml"
, Tuple.Create(Tuple.Create("", 786), Tuple.Create<System.Object, System.Int32>(item.UserId
            
            #line default
            #line hidden
, 786), false)
);

WriteLiteral(">");

            
            #line 22 "..\..\Views\MenuPolicy\Policy.cshtml"
                                                    Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 23 "..\..\Views\MenuPolicy\Policy.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </select>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label>Select an Office</label>\r\n                    <sele" +
"ct");

WriteLiteral(" id=\"OfficeSelect\"");

WriteLiteral(" class=\"ui search dropdown\"");

WriteLiteral(">\r\n                        <option>Select</option>\r\n");

            
            #line 30 "..\..\Views\MenuPolicy\Policy.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\MenuPolicy\Policy.cshtml"
                         foreach (var item in Model.Offices)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1241), Tuple.Create("\"", 1263)
            
            #line 32 "..\..\Views\MenuPolicy\Policy.cshtml"
, Tuple.Create(Tuple.Create("", 1249), Tuple.Create<System.Object, System.Int32>(item.OfficeId
            
            #line default
            #line hidden
, 1249), false)
);

WriteLiteral(">");

            
            #line 32 "..\..\Views\MenuPolicy\Policy.cshtml"
                                                      Write(item.OfficeCode);

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 32 "..\..\Views\MenuPolicy\Policy.cshtml"
                                                                        Write(item.OfficeName);

            
            #line default
            #line hidden
WriteLiteral(")</option>\r\n");

            
            #line 33 "..\..\Views\MenuPolicy\Policy.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </select>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label>&nbsp;</label>\r\n                    <button data-ge" +
"t-menu-policy-button");

WriteLiteral(" class=\"ui positive button\"");

WriteLiteral(">Load</button>\r\n                </div>\r\n            </div>\r\n        </div>\r\n\r\n   " +
"     <table");

WriteLiteral(" class=\"ui attached selector table tablesorter\"");

WriteLiteral(@">
            <thead>
            <tr>
                <th>
                    App
                </th>
                <th>
                    Menu Id
                </th>
                <th>
                    Menu Text
                </th>
                <th>
                    <input");

WriteLiteral(" id=\"AllowInputCheckbox\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-menu-allow data-toggle-allow/>\r\n                    <label");

WriteLiteral(" for=\"AllowInputCheckbox\"");

WriteLiteral(">Allow</label>\r\n                </th>\r\n                <th>\r\n                    " +
"<input");

WriteLiteral(" id=\"DenyInputCheckbox\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-menu-deny data-toggle-deny/>\r\n                    <label");

WriteLiteral(" for=\"DenyInputCheckbox\"");

WriteLiteral(">Deny</label>\r\n                </th>\r\n                <th>\r\n                    U" +
"rl\r\n                </th>\r\n            </tr>\r\n            </thead>\r\n            " +
"<tbody>\r\n");

            
            #line 69 "..\..\Views\MenuPolicy\Policy.cshtml"
            
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\MenuPolicy\Policy.cshtml"
             foreach (var item in Model.Menus)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 73 "..\..\Views\MenuPolicy\Policy.cshtml"
                   Write(item.AppName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 76 "..\..\Views\MenuPolicy\Policy.cshtml"
                   Write(item.MenuId);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 79 "..\..\Views\MenuPolicy\Policy.cshtml"
                   Write(item.MenuName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n                        <i" +
"nput");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" data-menu-allow");

WriteLiteral(" data-menu-id=\"");

            
            #line 82 "..\..\Views\MenuPolicy\Policy.cshtml"
                                                                     Write(item.MenuId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                    </td>\r\n                    <td>\r\n                        " +
"<input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" data-menu-deny");

WriteLiteral(" data-menu-id=\"");

            
            #line 85 "..\..\Views\MenuPolicy\Policy.cshtml"
                                                                    Write(item.MenuId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 88 "..\..\Views\MenuPolicy\Policy.cshtml"
                   Write(item.Url);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n");

            
            #line 91 "..\..\Views\MenuPolicy\Policy.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n        <div");

WriteLiteral(" class=\"vpad8\"");

WriteLiteral("></div>\r\n        <button data-save-button");

WriteLiteral(" class=\"ui positive button\"");

WriteLiteral(">Save</button>\r\n    </div>\r\n</div>\r\n<script");

WriteLiteral(" src=\"/Areas/Frapid.Authorization/Scripts/MenuPolicy/policy.js\"");

WriteLiteral("></script>");

        }
    }
}
#pragma warning restore 1591
