#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Frapid.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SubscriptionEmailTemplate/SubscriptionRemoved.cshtml")]
    public partial class _Views_SubscriptionEmailTemplate_SubscriptionRemoved_cshtml : System.Web.Mvc.WebViewPage<Frapid.WebsiteBuilder.ViewModels.Template>
    {
        public _Views_SubscriptionEmailTemplate_SubscriptionRemoved_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\SubscriptionEmailTemplate\SubscriptionRemoved.cshtml"
  
    ViewBag.Title = "Subscription Removed Email";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n<link");

WriteLiteral(" href=\"/my/template/css/site.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n<script");

WriteLiteral(" src=\"/Scripts/ace-1.2.2/src-min-noconflict/ace.js\"");

WriteLiteral("></script>\r\n<script>\r\n    var saveUrl = \"/dashboard/website/subscription/removed/" +
"save\";\r\n</script>\r\n");

            
            #line 12 "..\..\Views\SubscriptionEmailTemplate\SubscriptionRemoved.cshtml"
Write(Html.Partial("~/Areas/Frapid.WebsiteBuilder/Views/SubscriptionEmailTemplate/Shared/Editor.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
