#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Account;
    
    #line 1 "..\..\Views\Reset\Do.cshtml"
    using Frapid.i18n;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Reset/Do.cshtml")]
    public partial class _Views_Reset_Do_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Reset_Do_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Reset\Do.cshtml"
  
    ViewBag.Title = "Reset Your Account";
    Layout = ViewBag.LayoutPath + ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Reset\Do.cshtml"
 if (CultureManager.IsRtl())
{

            
            #line default
            #line hidden
WriteLiteral("    <link");

WriteLiteral(" rel=\"Stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 198), Tuple.Create("\"", 246)
            
            #line 10 "..\..\Views\Reset\Do.cshtml"
, Tuple.Create(Tuple.Create("", 205), Tuple.Create<System.Object, System.Int32>(Href("~/assets/css/master-page-rtl.css")
            
            #line default
            #line hidden
, 205), false)
);

WriteLiteral(" />\r\n");

            
            #line 11 "..\..\Views\Reset\Do.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <link");

WriteLiteral(" rel=\"Stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 290), Tuple.Create("\"", 334)
            
            #line 14 "..\..\Views\Reset\Do.cshtml"
, Tuple.Create(Tuple.Create("", 297), Tuple.Create<System.Object, System.Int32>(Href("~/assets/css/master-page.css")
            
            #line default
            #line hidden
, 297), false)
);

WriteLiteral(" />\r\n");

            
            #line 15 "..\..\Views\Reset\Do.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"ui attached padded reset password left aligned segment\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">Reset Your Account</div>\r\n        <div");

WriteLiteral(" class=\"ui stackable form\"");

WriteLiteral(" style=\"max-width: 400px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"PasswordInputPassword\"");

WriteLiteral(">Password</label>\r\n                    <input");

WriteLiteral(" type=\"password\"");

WriteLiteral("\r\n                           id=\"PasswordInputPassword\"");

WriteLiteral("\r\n                           required=\"\"");

WriteLiteral("\r\n                           maxlength=\"32\"");

WriteLiteral("\r\n                           data-validation-expression=\"^(?=.*\\d)(?=.*[a-z])(?=." +
"*[A-Z]).{6,32}$\"");

WriteLiteral("\r\n                           data-validation-message=\"Password should contain at " +
"least 6 characters with one uppercase, lowercase, and a number.\"");

WriteLiteral("\r\n                           data-validation-target=\".big.error\"");

WriteLiteral(" />\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"ConfirmPasswordInputPassword\"");

WriteLiteral(">Confirm Password</label>\r\n                    <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"ConfirmPasswordInputPassword\"");

WriteLiteral(" data-match-target=\"PasswordInputPassword\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" />\r\n                </div>\r\n\r\n\r\n\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"big error vpad8\"");

WriteLiteral("></div>\r\n        <button");

WriteLiteral(" class=\"ui positive button\"");

WriteLiteral(" id=\"SetPasswordButton\"");

WriteLiteral(">Set Password</button>\r\n        <a");

WriteLiteral(" class=\"ui negative button\"");

WriteLiteral(" href=\"/\"");

WriteLiteral(">Cancel</a>\r\n    </div>\r\n</div>\r\n<script");

WriteLiteral(" src=\"/i18n/resources.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/assets/js/backend.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/validator.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Areas/Frapid.Account/Scripts/Account/ResetConfirmation/index.js\"");

WriteLiteral("></script>\r\n");

        }
    }
}
#pragma warning restore 1591
