SELECT i18n.add_localized_resource('Titles', '', 'SignIn', 'Sign In');
SELECT i18n.add_localized_resource('Titles', '', 'Username', 'Username');
SELECT i18n.add_localized_resource('Titles', '', 'Password', 'Password');
SELECT i18n.add_localized_resource('Titles', '', 'ReturnToWebsite', 'Return to Website');
SELECT i18n.add_localized_resource('Titles', '', 'Or', 'Or');
SELECT i18n.add_localized_resource('Titles', '', 'Add', 'Add');
SELECT i18n.add_localized_resource('Titles', '', 'Save', 'Save');
SELECT i18n.add_localized_resource('Titles', '', 'Actions', 'Actions');
SELECT i18n.add_localized_resource('Titles', '', 'Edit', 'Edit');
SELECT i18n.add_localized_resource('Titles', '', 'Delete', 'Delete');
SELECT i18n.add_localized_resource('Titles', '', 'Update', 'Update');
SELECT i18n.add_localized_resource('Titles', '', 'Select', 'Select');
SELECT i18n.add_localized_resource('Titles', '', 'Approve', 'Approve');
SELECT i18n.add_localized_resource('Titles', '', 'Reject', 'Reject');
SELECT i18n.add_localized_resource('Titles', '', 'Close', 'Close');
SELECT i18n.add_localized_resource('Titles', '', 'ReturnToView', 'Return to View');
SELECT i18n.add_localized_resource('Titles', '', 'CreateDuplicate', 'Create Duplicate');
SELECT i18n.add_localized_resource('Titles', '', 'None', 'None');
SELECT i18n.add_localized_resource('Titles', '', 'First', 'First');
SELECT i18n.add_localized_resource('Titles', '', 'Previous', 'Previous');
SELECT i18n.add_localized_resource('Titles', '', 'Next', 'Next');
SELECT i18n.add_localized_resource('Titles', '', 'Last', 'Last');
SELECT i18n.add_localized_resource('Titles', '', 'Loading', 'Loading');
SELECT i18n.add_localized_resource('Titles', '', 'CreateAFlag', 'Create a Flag');
SELECT i18n.add_localized_resource('Titles', '', 'Update', 'Update');
SELECT i18n.add_localized_resource('Titles', '', 'CreateNew', 'Create New');
SELECT i18n.add_localized_resource('Titles', '', 'Verification', 'Verification');
SELECT i18n.add_localized_resource('Titles', '', 'Reason', 'Reason');
SELECT i18n.add_localized_resource('Titles', '', 'AddAKanbanList', 'Add a Kanban List');
SELECT i18n.add_localized_resource('Titles', '', 'KanbanId', 'KanbanId');
SELECT i18n.add_localized_resource('Titles', '', 'KanbanName', 'KanbanName');
SELECT i18n.add_localized_resource('Titles', '', 'Description', 'Description');
SELECT i18n.add_localized_resource('Titles', '', 'Cancel', 'Cancel');
SELECT i18n.add_localized_resource('Titles', '', 'OK', 'OK');
SELECT i18n.add_localized_resource('Titles', '', 'AddNew', 'Add New');
SELECT i18n.add_localized_resource('Titles', '', 'Flag', 'Flag');
SELECT i18n.add_localized_resource('Titles', '', 'Filter', 'Filter');
SELECT i18n.add_localized_resource('Titles', '', 'Export', 'Export');
SELECT i18n.add_localized_resource('Titles', '', 'ExportThisDocument', 'Export This Document');
SELECT i18n.add_localized_resource('Titles', '', 'ExportToDoc', 'Export to Doc');
SELECT i18n.add_localized_resource('Titles', '', 'ExportToExcel', 'Export to Excel');
SELECT i18n.add_localized_resource('Titles', '', 'ExportToPDF', 'Export to PDF');
SELECT i18n.add_localized_resource('Titles', '', 'Print', 'Print');
SELECT i18n.add_localized_resource('Titles', '', 'SelectAColumn', 'Select a Column');
SELECT i18n.add_localized_resource('Titles', '', 'FilterCondition', 'Filter Condition');
SELECT i18n.add_localized_resource('Titles', '', 'Value', 'Value');
SELECT i18n.add_localized_resource('Titles', '', 'And', 'And');
SELECT i18n.add_localized_resource('Titles', '', 'Add', 'Add');
SELECT i18n.add_localized_resource('Titles', '', 'Actions', 'Actions');
SELECT i18n.add_localized_resource('Titles', '', 'ColumnName', 'Column Name');
SELECT i18n.add_localized_resource('Titles', '', 'Condition', 'Condition');
SELECT i18n.add_localized_resource('Titles', '', 'SaveThisFilter', 'Save This Filter');
SELECT i18n.add_localized_resource('Titles', '', 'FilterName', 'Filter Name');
SELECT i18n.add_localized_resource('Titles', '', 'Save', 'Save');
SELECT i18n.add_localized_resource('Titles', '', 'ManageFilters', 'Manage Filters');
SELECT i18n.add_localized_resource('Titles', '', 'RemoveAsDefault', 'Remove As Default');
SELECT i18n.add_localized_resource('Titles', '', 'MakeAsDefault', 'Make As Default');
SELECT i18n.add_localized_resource('Titles', '', 'DataImport', 'Data Import');
SELECT i18n.add_localized_resource('Titles', '', 'ExportData', 'Export Data');
SELECT i18n.add_localized_resource('Titles', '', 'ImportData', 'Import Data');
SELECT i18n.add_localized_resource('Titles', '', 'Yes', 'Yes');
SELECT i18n.add_localized_resource('Titles', '', 'No', 'No');
SELECT i18n.add_localized_resource('Titles', '', 'View', 'View');
SELECT i18n.add_localized_resource('Titles', '', 'Rating', 'Rating');
SELECT i18n.add_localized_resource('Titles', '', 'AddNewChecklist', 'Add New Checklist');
SELECT i18n.add_localized_resource('Titles', '', 'EditThisChecklist', 'Edit This Checklist');
SELECT i18n.add_localized_resource('Titles', '', 'DeleteThisChecklist', 'Delete This Checklist');
SELECT i18n.add_localized_resource('Titles', '', 'Verify', 'Verify');
SELECT i18n.add_localized_resource('Titles', '', 'Back', 'Back');
SELECT i18n.add_localized_resource('Titles', '', 'PageN', 'Page {0}');
SELECT i18n.add_localized_resource('Titles', '', 'SelectAFilter', 'Select a Filter');
SELECT i18n.add_localized_resource('Titles', '', 'CustomFields', 'Custom Fields');
SELECT i18n.add_localized_resource('Titles', '', 'Untitled', 'Untitled');
SELECT i18n.add_localized_resource('Labels', '', 'UploadInvalidTryAgain', 'Your upload is of invalid file type "{0}". Please try again.');
SELECT i18n.add_localized_resource('Labels', '', 'ProcessingYourCSVFile', 'Processing  your CSV file.');
SELECT i18n.add_localized_resource('Labels', '', 'FlagSaved', 'Flag was saved.');
SELECT i18n.add_localized_resource('Labels', '', 'SuccessfullyProcessedYourFile', 'Successfully processed your file.');
SELECT i18n.add_localized_resource('Labels', '', 'FlagRemoved', 'Flag was removed.');
SELECT i18n.add_localized_resource('Labels', '', 'RequestingImport', 'Requesting import. This may take several minutes to complete.');
SELECT i18n.add_localized_resource('Labels', '', 'NoFormFound', 'No instance of form was found.');
SELECT i18n.add_localized_resource('Labels', '', 'ImportedNItems', 'Successfully imported {0} items.');
SELECT i18n.add_localized_resource('Labels', '', 'RollingBackChanges', 'Rolling back changes.');
SELECT i18n.add_localized_resource('Warnings', '', 'InvalidFileExtension', 'Invalid file extension.');
SELECT i18n.add_localized_resource('Questions', '', 'AreYouSure', 'Are you sure?');
SELECT i18n.add_localized_resource('Questions', '', 'ColumnInvalidAreYouSure', 'The column "{0}" does not exist or is invalid. Are you sure you want to continue?');
SELECT i18n.add_localized_resource('Questions', '', 'TaskCompletedSuccessfullyReturnToView', 'Task completed successfully. Return to view?');
SELECT i18n.add_localized_resource('Labels', '', 'NHours', '{0} hour(s).');
SELECT i18n.add_localized_resource('Labels', '', 'NMinutes', '{0} minute(s).');
SELECT i18n.add_localized_resource('Labels', '', 'ItemDuplicated', 'Item duplicated.');
SELECT i18n.add_localized_resource('Labels', '', 'TaskCompletedSuccessfully', 'Task completed successfully.');
SELECT i18n.add_localized_resource('Labels', '', 'ThisFieldIsRequired', 'This field is required.');
SELECT i18n.add_localized_resource('Labels', '', 'NamedFilter', 'Filter: {0}.');
SELECT i18n.add_localized_resource('DbErrors', '', 'TableNotFound', 'The table was not found.');
